name = "dots-ca-fe"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = true

[vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_API_URL = "http://localhost:8001"

[assets]
directory = "./.vercel/output/static"
binding = "ASSETS"
