import { SlikData, DebtEntry } from './types';

export const mockSlikData: SlikData = {
    header: {
        nomorReferensi: "REF-2026-001234",
        tanggalPermintaan: "05/03/2026",
        waktuPermintaan: "10:30:00",
        jenisPencarian: "Individual",
        tujuanPermintaan: "Permohonan Kredit",
    },
    individual: {
        dataPokokDebitur: [
            {
                namaDebitur: "AHMAD FAUZI",
                jenisPenggunaanAkhir: "Konsumsi",
                noIdentitas: "3276055208850005",
                jenisIdentitas: "KTP",
                tempatLahir: "JAKARTA",
                tanggalLahir: "12/08/1985",
                jenisKelamin: "Laki-laki",
                statusPerkawinan: "Kawin",
                pendidikan: "S1",
                pekerjaan: "Karyawan Swasta",
                bidangUsaha: "Perdagangan",
                alamat: "Jl. Melati No. 15 RT 003/005",
                kelurahan: "Cipinang Muara",
                kecamatan: "Jatinegara",
                kota: "Jakarta Timur",
                kodePos: "13420",
                noTelp: "081234567890",
                npwp: "12.345.678.9-012.000",
                namaPerusahaan: "PT Maju Jaya",
                noId: "DEB-001",
            },
        ],
        ringkasanFasilitas: {
            totalPlafon: "150.000.000",
            totalBakiDebet: "45.200.000",
            totalTunggakan: "0",
            kondisiTerburuk: "1",
            jumlahFasilitas: "3",
            jumlahPemberiKredit: "2",
        },
        fasilitas: {
            kreditPembiayan: [
                {
                    pelapor: "BANK MANDIRI",
                    cabangPelapor: "KCP Jakarta Timur",
                    jenisPenggunaanAkhir: "Kredit Multiguna",
                    tanggalDibentuk: "15/01/2024",
                    tanggalJatuhTempo: "15/01/2027",
                    plafon: "50.000.000",
                    realisasi: "50.000.000",
                    bakiDebet: "25.200.000",
                    tunggakan: "0",
                    kondisi: "Lancar",
                    frekuensiTunggakan: "0",
                    nilaiAgunan: "75.000.000",
                    kolektibilitasBulanan: [
                        { bulan: "Feb 2026", kolektibilitas: "1" },
                        { bulan: "Jan 2026", kolektibilitas: "1" },
                        { bulan: "Des 2025", kolektibilitas: "1" },
                        { bulan: "Nov 2025", kolektibilitas: "1" },
                        { bulan: "Okt 2025", kolektibilitas: "1" },
                        { bulan: "Sep 2025", kolektibilitas: "1" },
                        { bulan: "Agu 2025", kolektibilitas: "1" },
                        { bulan: "Jul 2025", kolektibilitas: "1" },
                        { bulan: "Jun 2025", kolektibilitas: "1" },
                        { bulan: "Mei 2025", kolektibilitas: "1" },
                        { bulan: "Apr 2025", kolektibilitas: "1" },
                        { bulan: "Mar 2025", kolektibilitas: "1" },
                        { bulan: "Feb 2025", kolektibilitas: "1" },
                        { bulan: "Jan 2025", kolektibilitas: "1" },
                        { bulan: "Des 2024", kolektibilitas: "1" },
                        { bulan: "Nov 2024", kolektibilitas: "1" },
                        { bulan: "Okt 2024", kolektibilitas: "1" },
                        { bulan: "Sep 2024", kolektibilitas: "1" },
                        { bulan: "Agu 2024", kolektibilitas: "1" },
                        { bulan: "Jul 2024", kolektibilitas: "1" },
                        { bulan: "Jun 2024", kolektibilitas: "1" },
                        { bulan: "Mei 2024", kolektibilitas: "1" },
                        { bulan: "Apr 2024", kolektibilitas: "1" },
                        { bulan: "Mar 2024", kolektibilitas: "1" },
                    ],
                    agunan: [
                        { jenisAgunan: "BPKB Kendaraan", nilaiAgunan: "75.000.000", noAgunan: "AGN-001" },
                    ],
                    penjamin: [],
                },
                {
                    pelapor: "BANK MANDIRI",
                    cabangPelapor: "KCP Jakarta Timur",
                    jenisPenggunaanAkhir: "KPR",
                    tanggalDibentuk: "20/06/2022",
                    tanggalJatuhTempo: "20/06/2032",
                    plafon: "80.000.000",
                    realisasi: "80.000.000",
                    bakiDebet: "20.000.000",
                    tunggakan: "0",
                    kondisi: "Lancar",
                    frekuensiTunggakan: "0",
                    nilaiAgunan: "150.000.000",
                    kolektibilitasBulanan: [
                        { bulan: "Feb 2026", kolektibilitas: "1" },
                        { bulan: "Jan 2026", kolektibilitas: "1" },
                        { bulan: "Des 2025", kolektibilitas: "1" },
                        { bulan: "Nov 2025", kolektibilitas: "1" },
                        { bulan: "Okt 2025", kolektibilitas: "1" },
                        { bulan: "Sep 2025", kolektibilitas: "1" },
                        { bulan: "Agu 2025", kolektibilitas: "1" },
                        { bulan: "Jul 2025", kolektibilitas: "1" },
                        { bulan: "Jun 2025", kolektibilitas: "1" },
                        { bulan: "Mei 2025", kolektibilitas: "1" },
                        { bulan: "Apr 2025", kolektibilitas: "1" },
                        { bulan: "Mar 2025", kolektibilitas: "2" },
                        { bulan: "Feb 2025", kolektibilitas: "1" },
                        { bulan: "Jan 2025", kolektibilitas: "1" },
                        { bulan: "Des 2024", kolektibilitas: "1" },
                        { bulan: "Nov 2024", kolektibilitas: "1" },
                        { bulan: "Okt 2024", kolektibilitas: "1" },
                        { bulan: "Sep 2024", kolektibilitas: "1" },
                        { bulan: "Agu 2024", kolektibilitas: "1" },
                        { bulan: "Jul 2024", kolektibilitas: "1" },
                        { bulan: "Jun 2024", kolektibilitas: "1" },
                        { bulan: "Mei 2024", kolektibilitas: "1" },
                        { bulan: "Apr 2024", kolektibilitas: "1" },
                        { bulan: "Mar 2024", kolektibilitas: "1" },
                    ],
                    agunan: [
                        { jenisAgunan: "SHM Tanah & Bangunan", nilaiAgunan: "150.000.000", noAgunan: "AGN-002" },
                    ],
                    penjamin: [
                        { namaPenjamin: "SITI NURHALIZA", jenisIdentitas: "KTP", noIdentitas: "3276055208860012" },
                    ],
                },
                {
                    pelapor: "BRI",
                    cabangPelapor: "Unit Jatinegara",
                    jenisPenggunaanAkhir: "KUR Mikro",
                    tanggalDibentuk: "10/03/2023",
                    tanggalJatuhTempo: "10/03/2026",
                    plafon: "20.000.000",
                    realisasi: "20.000.000",
                    bakiDebet: "0",
                    tunggakan: "0",
                    kondisi: "Lunas",
                    frekuensiTunggakan: "2",
                    nilaiAgunan: "0",
                    kolektibilitasBulanan: [
                        { bulan: "Feb 2026", kolektibilitas: "0" },
                        { bulan: "Jan 2026", kolektibilitas: "0" },
                        { bulan: "Des 2025", kolektibilitas: "0" },
                        { bulan: "Nov 2025", kolektibilitas: "0" },
                        { bulan: "Okt 2025", kolektibilitas: "1" },
                        { bulan: "Sep 2025", kolektibilitas: "1" },
                        { bulan: "Agu 2025", kolektibilitas: "2" },
                        { bulan: "Jul 2025", kolektibilitas: "2" },
                        { bulan: "Jun 2025", kolektibilitas: "1" },
                        { bulan: "Mei 2025", kolektibilitas: "1" },
                        { bulan: "Apr 2025", kolektibilitas: "1" },
                        { bulan: "Mar 2025", kolektibilitas: "1" },
                        { bulan: "Feb 2025", kolektibilitas: "1" },
                        { bulan: "Jan 2025", kolektibilitas: "1" },
                        { bulan: "Des 2024", kolektibilitas: "1" },
                        { bulan: "Nov 2024", kolektibilitas: "1" },
                        { bulan: "Okt 2024", kolektibilitas: "1" },
                        { bulan: "Sep 2024", kolektibilitas: "1" },
                        { bulan: "Agu 2024", kolektibilitas: "1" },
                        { bulan: "Jul 2024", kolektibilitas: "1" },
                        { bulan: "Jun 2024", kolektibilitas: "1" },
                        { bulan: "Mei 2024", kolektibilitas: "1" },
                        { bulan: "Apr 2024", kolektibilitas: "1" },
                        { bulan: "Mar 2024", kolektibilitas: "1" },
                    ],
                    agunan: [],
                    penjamin: [],
                },
            ],
        },
    },
};

export const mockSurveyDebts: DebtEntry[] = [
    {
        id: 'survey-1',
        source: 'survey',
        creditor: 'Koperasi Sejahtera',
        plafon: 'Rp 5.000.000',
        bakiDebet: 'Rp 2.500.000',
        dueDate: '15 Jun 2026',
        status: 'Lancar',
        kondisi: '1',
    },
    {
        id: 'survey-2',
        source: 'survey',
        creditor: 'Tetangga (Pak Budi)',
        plafon: 'Rp 3.000.000',
        bakiDebet: 'Rp 1.000.000',
        dueDate: '-',
        status: 'Lancar',
        kondisi: '1',
    },
];

import { formatThousands } from '@/shared/lib/utils';

export function formatRupiah(value: string): string {
    if (!value) return 'Rp 0';
    const num = value.replace(/[^\d.-]/g, '');
    if (isNaN(Number(num))) return value;
    return 'Rp ' + formatThousands(num);
}

export function slikToDebtEntries(slik: SlikData): DebtEntry[] {
    return slik.individual.fasilitas.kreditPembiayan.map((k, i) => ({
        id: `slik-${i}`,
        source: 'credit-bureau' as const,
        creditor: k.pelapor,
        plafon: formatRupiah(k.plafon),
        bakiDebet: formatRupiah(k.bakiDebet),
        dueDate: k.tanggalJatuhTempo,
        status: k.kondisi,
        kondisi: k.kolektibilitasBulanan[0]?.kolektibilitas || '-',
        detail: k,
    }));
}
