// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: reference/v1/reference.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationReferenceServiceGetLoanProduct = "/api.reference.v1.ReferenceService/GetLoanProduct"
const OperationReferenceServiceListApplicationStatuses = "/api.reference.v1.ReferenceService/ListApplicationStatuses"
const OperationReferenceServiceListAttributeRegistry = "/api.reference.v1.ReferenceService/ListAttributeRegistry"
const OperationReferenceServiceListBranches = "/api.reference.v1.ReferenceService/ListBranches"
const OperationReferenceServiceListFinancialGLAccounts = "/api.reference.v1.ReferenceService/ListFinancialGLAccounts"
const OperationReferenceServiceListLoanOfficers = "/api.reference.v1.ReferenceService/ListLoanOfficers"
const OperationReferenceServiceListLoanProducts = "/api.reference.v1.ReferenceService/ListLoanProducts"
const OperationReferenceServiceListSurveyTemplates = "/api.reference.v1.ReferenceService/ListSurveyTemplates"

type ReferenceServiceHTTPServer interface {
	GetLoanProduct(context.Context, *GetLoanProductRequest) (*LoanProduct, error)
	ListApplicationStatuses(context.Context, *emptypb.Empty) (*ListApplicationStatusesResponse, error)
	ListAttributeRegistry(context.Context, *emptypb.Empty) (*ListAttributeRegistryResponse, error)
	ListBranches(context.Context, *emptypb.Empty) (*ListBranchesResponse, error)
	ListFinancialGLAccounts(context.Context, *emptypb.Empty) (*ListFinancialGLAccountsResponse, error)
	ListLoanOfficers(context.Context, *ListLoanOfficersRequest) (*ListLoanOfficersResponse, error)
	ListLoanProducts(context.Context, *emptypb.Empty) (*ListLoanProductsResponse, error)
	ListSurveyTemplates(context.Context, *ListSurveyTemplatesRequest) (*ListSurveyTemplatesResponse, error)
}

func RegisterReferenceServiceHTTPServer(s *http.Server, srv ReferenceServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/reference/loan-products", _ReferenceService_ListLoanProducts0_HTTP_Handler(srv))
	r.GET("/v1/reference/loan-products/{id}", _ReferenceService_GetLoanProduct0_HTTP_Handler(srv))
	r.GET("/v1/reference/branches", _ReferenceService_ListBranches0_HTTP_Handler(srv))
	r.GET("/v1/reference/branches/{branch_code}/officers", _ReferenceService_ListLoanOfficers0_HTTP_Handler(srv))
	r.GET("/v1/reference/application-statuses", _ReferenceService_ListApplicationStatuses0_HTTP_Handler(srv))
	r.GET("/v1/reference/attribute-registry", _ReferenceService_ListAttributeRegistry0_HTTP_Handler(srv))
	r.GET("/v1/reference/survey-templates", _ReferenceService_ListSurveyTemplates0_HTTP_Handler(srv))
	r.GET("/v1/reference/gl-accounts", _ReferenceService_ListFinancialGLAccounts0_HTTP_Handler(srv))
}

func _ReferenceService_ListLoanProducts0_HTTP_Handler(srv ReferenceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceServiceListLoanProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLoanProducts(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLoanProductsResponse)
		return ctx.Result(200, reply)
	}
}

func _ReferenceService_GetLoanProduct0_HTTP_Handler(srv ReferenceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLoanProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceServiceGetLoanProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLoanProduct(ctx, req.(*GetLoanProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoanProduct)
		return ctx.Result(200, reply)
	}
}

func _ReferenceService_ListBranches0_HTTP_Handler(srv ReferenceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceServiceListBranches)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBranches(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBranchesResponse)
		return ctx.Result(200, reply)
	}
}

func _ReferenceService_ListLoanOfficers0_HTTP_Handler(srv ReferenceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLoanOfficersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceServiceListLoanOfficers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLoanOfficers(ctx, req.(*ListLoanOfficersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLoanOfficersResponse)
		return ctx.Result(200, reply)
	}
}

func _ReferenceService_ListApplicationStatuses0_HTTP_Handler(srv ReferenceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceServiceListApplicationStatuses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApplicationStatuses(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApplicationStatusesResponse)
		return ctx.Result(200, reply)
	}
}

func _ReferenceService_ListAttributeRegistry0_HTTP_Handler(srv ReferenceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceServiceListAttributeRegistry)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAttributeRegistry(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAttributeRegistryResponse)
		return ctx.Result(200, reply)
	}
}

func _ReferenceService_ListSurveyTemplates0_HTTP_Handler(srv ReferenceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSurveyTemplatesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceServiceListSurveyTemplates)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSurveyTemplates(ctx, req.(*ListSurveyTemplatesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSurveyTemplatesResponse)
		return ctx.Result(200, reply)
	}
}

func _ReferenceService_ListFinancialGLAccounts0_HTTP_Handler(srv ReferenceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferenceServiceListFinancialGLAccounts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFinancialGLAccounts(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFinancialGLAccountsResponse)
		return ctx.Result(200, reply)
	}
}

type ReferenceServiceHTTPClient interface {
	GetLoanProduct(ctx context.Context, req *GetLoanProductRequest, opts ...http.CallOption) (rsp *LoanProduct, err error)
	ListApplicationStatuses(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListApplicationStatusesResponse, err error)
	ListAttributeRegistry(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListAttributeRegistryResponse, err error)
	ListBranches(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListBranchesResponse, err error)
	ListFinancialGLAccounts(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListFinancialGLAccountsResponse, err error)
	ListLoanOfficers(ctx context.Context, req *ListLoanOfficersRequest, opts ...http.CallOption) (rsp *ListLoanOfficersResponse, err error)
	ListLoanProducts(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListLoanProductsResponse, err error)
	ListSurveyTemplates(ctx context.Context, req *ListSurveyTemplatesRequest, opts ...http.CallOption) (rsp *ListSurveyTemplatesResponse, err error)
}

type ReferenceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewReferenceServiceHTTPClient(client *http.Client) ReferenceServiceHTTPClient {
	return &ReferenceServiceHTTPClientImpl{client}
}

func (c *ReferenceServiceHTTPClientImpl) GetLoanProduct(ctx context.Context, in *GetLoanProductRequest, opts ...http.CallOption) (*LoanProduct, error) {
	var out LoanProduct
	pattern := "/v1/reference/loan-products/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceServiceGetLoanProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceServiceHTTPClientImpl) ListApplicationStatuses(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListApplicationStatusesResponse, error) {
	var out ListApplicationStatusesResponse
	pattern := "/v1/reference/application-statuses"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceServiceListApplicationStatuses))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceServiceHTTPClientImpl) ListAttributeRegistry(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListAttributeRegistryResponse, error) {
	var out ListAttributeRegistryResponse
	pattern := "/v1/reference/attribute-registry"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceServiceListAttributeRegistry))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceServiceHTTPClientImpl) ListBranches(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListBranchesResponse, error) {
	var out ListBranchesResponse
	pattern := "/v1/reference/branches"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceServiceListBranches))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceServiceHTTPClientImpl) ListFinancialGLAccounts(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListFinancialGLAccountsResponse, error) {
	var out ListFinancialGLAccountsResponse
	pattern := "/v1/reference/gl-accounts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceServiceListFinancialGLAccounts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceServiceHTTPClientImpl) ListLoanOfficers(ctx context.Context, in *ListLoanOfficersRequest, opts ...http.CallOption) (*ListLoanOfficersResponse, error) {
	var out ListLoanOfficersResponse
	pattern := "/v1/reference/branches/{branch_code}/officers"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceServiceListLoanOfficers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceServiceHTTPClientImpl) ListLoanProducts(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListLoanProductsResponse, error) {
	var out ListLoanProductsResponse
	pattern := "/v1/reference/loan-products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceServiceListLoanProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ReferenceServiceHTTPClientImpl) ListSurveyTemplates(ctx context.Context, in *ListSurveyTemplatesRequest, opts ...http.CallOption) (*ListSurveyTemplatesResponse, error) {
	var out ListSurveyTemplatesResponse
	pattern := "/v1/reference/survey-templates"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferenceServiceListSurveyTemplates))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
