// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: reference/v1/reference.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoanProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductCode   string                 `protobuf:"bytes,2,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Segment       string                 `protobuf:"bytes,4,opt,name=segment,proto3" json:"segment,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanProduct) Reset() {
	*x = LoanProduct{}
	mi := &file_reference_v1_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanProduct) ProtoMessage() {}

func (x *LoanProduct) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanProduct.ProtoReflect.Descriptor instead.
func (*LoanProduct) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{0}
}

func (x *LoanProduct) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoanProduct) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *LoanProduct) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *LoanProduct) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *LoanProduct) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchCode    string                 `protobuf:"bytes,1,opt,name=branch_code,json=branchCode,proto3" json:"branch_code,omitempty"`
	BranchName    string                 `protobuf:"bytes,2,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	RegionCode    string                 `protobuf:"bytes,3,opt,name=region_code,json=regionCode,proto3" json:"region_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_reference_v1_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{1}
}

func (x *Branch) GetBranchCode() string {
	if x != nil {
		return x.BranchCode
	}
	return ""
}

func (x *Branch) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *Branch) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

type LoanOfficer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OfficerCode   string                 `protobuf:"bytes,2,opt,name=officer_code,json=officerCode,proto3" json:"officer_code,omitempty"`
	BranchCode    string                 `protobuf:"bytes,3,opt,name=branch_code,json=branchCode,proto3" json:"branch_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoanOfficer) Reset() {
	*x = LoanOfficer{}
	mi := &file_reference_v1_reference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoanOfficer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoanOfficer) ProtoMessage() {}

func (x *LoanOfficer) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoanOfficer.ProtoReflect.Descriptor instead.
func (*LoanOfficer) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{2}
}

func (x *LoanOfficer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoanOfficer) GetOfficerCode() string {
	if x != nil {
		return x.OfficerCode
	}
	return ""
}

func (x *LoanOfficer) GetBranchCode() string {
	if x != nil {
		return x.BranchCode
	}
	return ""
}

type ApplicationStatusRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    string                 `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusGroup   string                 `protobuf:"bytes,2,opt,name=status_group,json=statusGroup,proto3" json:"status_group,omitempty"`
	IsTerminal    bool                   `protobuf:"varint,3,opt,name=is_terminal,json=isTerminal,proto3" json:"is_terminal,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationStatusRef) Reset() {
	*x = ApplicationStatusRef{}
	mi := &file_reference_v1_reference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationStatusRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationStatusRef) ProtoMessage() {}

func (x *ApplicationStatusRef) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationStatusRef.ProtoReflect.Descriptor instead.
func (*ApplicationStatusRef) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{3}
}

func (x *ApplicationStatusRef) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *ApplicationStatusRef) GetStatusGroup() string {
	if x != nil {
		return x.StatusGroup
	}
	return ""
}

func (x *ApplicationStatusRef) GetIsTerminal() bool {
	if x != nil {
		return x.IsTerminal
	}
	return false
}

func (x *ApplicationStatusRef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AttributeRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttrKey       string                 `protobuf:"bytes,1,opt,name=attr_key,json=attrKey,proto3" json:"attr_key,omitempty"`
	AttrName      string                 `protobuf:"bytes,2,opt,name=attr_name,json=attrName,proto3" json:"attr_name,omitempty"`
	DataType      string                 `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeRegistry) Reset() {
	*x = AttributeRegistry{}
	mi := &file_reference_v1_reference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeRegistry) ProtoMessage() {}

func (x *AttributeRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeRegistry.ProtoReflect.Descriptor instead.
func (*AttributeRegistry) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{4}
}

func (x *AttributeRegistry) GetAttrKey() string {
	if x != nil {
		return x.AttrKey
	}
	return ""
}

func (x *AttributeRegistry) GetAttrName() string {
	if x != nil {
		return x.AttrName
	}
	return ""
}

func (x *AttributeRegistry) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *AttributeRegistry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AttributeRegistry) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type SurveyTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	TemplateName  string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	ApplicantType string                 `protobuf:"bytes,4,opt,name=applicant_type,json=applicantType,proto3" json:"applicant_type,omitempty"`
	ProductId     string                 `protobuf:"bytes,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyTemplate) Reset() {
	*x = SurveyTemplate{}
	mi := &file_reference_v1_reference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyTemplate) ProtoMessage() {}

func (x *SurveyTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyTemplate.ProtoReflect.Descriptor instead.
func (*SurveyTemplate) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{5}
}

func (x *SurveyTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SurveyTemplate) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SurveyTemplate) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *SurveyTemplate) GetApplicantType() string {
	if x != nil {
		return x.ApplicantType
	}
	return ""
}

func (x *SurveyTemplate) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type FinancialGLAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlCode        string                 `protobuf:"bytes,1,opt,name=gl_code,json=glCode,proto3" json:"gl_code,omitempty"`
	GlName        string                 `protobuf:"bytes,2,opt,name=gl_name,json=glName,proto3" json:"gl_name,omitempty"`
	StatementType string                 `protobuf:"bytes,3,opt,name=statement_type,json=statementType,proto3" json:"statement_type,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Sign          int32                  `protobuf:"varint,5,opt,name=sign,proto3" json:"sign,omitempty"`
	IsDebtService bool                   `protobuf:"varint,6,opt,name=is_debt_service,json=isDebtService,proto3" json:"is_debt_service,omitempty"`
	IsOperating   bool                   `protobuf:"varint,7,opt,name=is_operating,json=isOperating,proto3" json:"is_operating,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinancialGLAccount) Reset() {
	*x = FinancialGLAccount{}
	mi := &file_reference_v1_reference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialGLAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialGLAccount) ProtoMessage() {}

func (x *FinancialGLAccount) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialGLAccount.ProtoReflect.Descriptor instead.
func (*FinancialGLAccount) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{6}
}

func (x *FinancialGLAccount) GetGlCode() string {
	if x != nil {
		return x.GlCode
	}
	return ""
}

func (x *FinancialGLAccount) GetGlName() string {
	if x != nil {
		return x.GlName
	}
	return ""
}

func (x *FinancialGLAccount) GetStatementType() string {
	if x != nil {
		return x.StatementType
	}
	return ""
}

func (x *FinancialGLAccount) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FinancialGLAccount) GetSign() int32 {
	if x != nil {
		return x.Sign
	}
	return 0
}

func (x *FinancialGLAccount) GetIsDebtService() bool {
	if x != nil {
		return x.IsDebtService
	}
	return false
}

func (x *FinancialGLAccount) GetIsOperating() bool {
	if x != nil {
		return x.IsOperating
	}
	return false
}

func (x *FinancialGLAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetLoanProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanProductRequest) Reset() {
	*x = GetLoanProductRequest{}
	mi := &file_reference_v1_reference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanProductRequest) ProtoMessage() {}

func (x *GetLoanProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanProductRequest.ProtoReflect.Descriptor instead.
func (*GetLoanProductRequest) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{7}
}

func (x *GetLoanProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListLoanProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*LoanProduct         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanProductsResponse) Reset() {
	*x = ListLoanProductsResponse{}
	mi := &file_reference_v1_reference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanProductsResponse) ProtoMessage() {}

func (x *ListLoanProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanProductsResponse.ProtoReflect.Descriptor instead.
func (*ListLoanProductsResponse) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{8}
}

func (x *ListLoanProductsResponse) GetProducts() []*LoanProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

type ListBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*Branch              `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesResponse) Reset() {
	*x = ListBranchesResponse{}
	mi := &file_reference_v1_reference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesResponse) ProtoMessage() {}

func (x *ListBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListBranchesResponse) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{9}
}

func (x *ListBranchesResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type ListLoanOfficersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchCode    string                 `protobuf:"bytes,1,opt,name=branch_code,json=branchCode,proto3" json:"branch_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanOfficersRequest) Reset() {
	*x = ListLoanOfficersRequest{}
	mi := &file_reference_v1_reference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanOfficersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanOfficersRequest) ProtoMessage() {}

func (x *ListLoanOfficersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanOfficersRequest.ProtoReflect.Descriptor instead.
func (*ListLoanOfficersRequest) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{10}
}

func (x *ListLoanOfficersRequest) GetBranchCode() string {
	if x != nil {
		return x.BranchCode
	}
	return ""
}

type ListLoanOfficersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Officers      []*LoanOfficer         `protobuf:"bytes,1,rep,name=officers,proto3" json:"officers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoanOfficersResponse) Reset() {
	*x = ListLoanOfficersResponse{}
	mi := &file_reference_v1_reference_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoanOfficersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoanOfficersResponse) ProtoMessage() {}

func (x *ListLoanOfficersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoanOfficersResponse.ProtoReflect.Descriptor instead.
func (*ListLoanOfficersResponse) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{11}
}

func (x *ListLoanOfficersResponse) GetOfficers() []*LoanOfficer {
	if x != nil {
		return x.Officers
	}
	return nil
}

type ListApplicationStatusesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Statuses      []*ApplicationStatusRef `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationStatusesResponse) Reset() {
	*x = ListApplicationStatusesResponse{}
	mi := &file_reference_v1_reference_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationStatusesResponse) ProtoMessage() {}

func (x *ListApplicationStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationStatusesResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationStatusesResponse) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{12}
}

func (x *ListApplicationStatusesResponse) GetStatuses() []*ApplicationStatusRef {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ListAttributeRegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*AttributeRegistry   `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributeRegistryResponse) Reset() {
	*x = ListAttributeRegistryResponse{}
	mi := &file_reference_v1_reference_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributeRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributeRegistryResponse) ProtoMessage() {}

func (x *ListAttributeRegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributeRegistryResponse.ProtoReflect.Descriptor instead.
func (*ListAttributeRegistryResponse) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{13}
}

func (x *ListAttributeRegistryResponse) GetAttributes() []*AttributeRegistry {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ListSurveyTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeadType      string                 `protobuf:"bytes,1,opt,name=head_type,json=headType,proto3" json:"head_type,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSurveyTemplatesRequest) Reset() {
	*x = ListSurveyTemplatesRequest{}
	mi := &file_reference_v1_reference_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSurveyTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSurveyTemplatesRequest) ProtoMessage() {}

func (x *ListSurveyTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSurveyTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListSurveyTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{14}
}

func (x *ListSurveyTemplatesRequest) GetHeadType() string {
	if x != nil {
		return x.HeadType
	}
	return ""
}

func (x *ListSurveyTemplatesRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ListSurveyTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*SurveyTemplate      `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSurveyTemplatesResponse) Reset() {
	*x = ListSurveyTemplatesResponse{}
	mi := &file_reference_v1_reference_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSurveyTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSurveyTemplatesResponse) ProtoMessage() {}

func (x *ListSurveyTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSurveyTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListSurveyTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{15}
}

func (x *ListSurveyTemplatesResponse) GetTemplates() []*SurveyTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type ListFinancialGLAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*FinancialGLAccount  `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinancialGLAccountsResponse) Reset() {
	*x = ListFinancialGLAccountsResponse{}
	mi := &file_reference_v1_reference_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinancialGLAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinancialGLAccountsResponse) ProtoMessage() {}

func (x *ListFinancialGLAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reference_v1_reference_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinancialGLAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListFinancialGLAccountsResponse) Descriptor() ([]byte, []int) {
	return file_reference_v1_reference_proto_rawDescGZIP(), []int{16}
}

func (x *ListFinancialGLAccountsResponse) GetAccounts() []*FinancialGLAccount {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_reference_v1_reference_proto protoreflect.FileDescriptor

const file_reference_v1_reference_proto_rawDesc = "" +
	"\n" +
	"\x1creference/v1/reference.proto\x12\x10api.reference.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x95\x01\n" +
	"\vLoanProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fproduct_code\x18\x02 \x01(\tR\vproductCode\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x18\n" +
	"\asegment\x18\x04 \x01(\tR\asegment\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"k\n" +
	"\x06Branch\x12\x1f\n" +
	"\vbranch_code\x18\x01 \x01(\tR\n" +
	"branchCode\x12\x1f\n" +
	"\vbranch_name\x18\x02 \x01(\tR\n" +
	"branchName\x12\x1f\n" +
	"\vregion_code\x18\x03 \x01(\tR\n" +
	"regionCode\"a\n" +
	"\vLoanOfficer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fofficer_code\x18\x02 \x01(\tR\vofficerCode\x12\x1f\n" +
	"\vbranch_code\x18\x03 \x01(\tR\n" +
	"branchCode\"\x9d\x01\n" +
	"\x14ApplicationStatusRef\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\tR\n" +
	"statusCode\x12!\n" +
	"\fstatus_group\x18\x02 \x01(\tR\vstatusGroup\x12\x1f\n" +
	"\vis_terminal\x18\x03 \x01(\bR\n" +
	"isTerminal\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xa0\x01\n" +
	"\x11AttributeRegistry\x12\x19\n" +
	"\battr_key\x18\x01 \x01(\tR\aattrKey\x12\x1b\n" +
	"\tattr_name\x18\x02 \x01(\tR\battrName\x12\x1b\n" +
	"\tdata_type\x18\x03 \x01(\tR\bdataType\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\"\xb0\x01\n" +
	"\x0eSurveyTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12%\n" +
	"\x0eapplicant_type\x18\x04 \x01(\tR\rapplicantType\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\tR\tproductId\"\x8a\x02\n" +
	"\x12FinancialGLAccount\x12\x17\n" +
	"\agl_code\x18\x01 \x01(\tR\x06glCode\x12\x17\n" +
	"\agl_name\x18\x02 \x01(\tR\x06glName\x12%\n" +
	"\x0estatement_type\x18\x03 \x01(\tR\rstatementType\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04sign\x18\x05 \x01(\x05R\x04sign\x12&\n" +
	"\x0fis_debt_service\x18\x06 \x01(\bR\risDebtService\x12!\n" +
	"\fis_operating\x18\a \x01(\bR\visOperating\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"'\n" +
	"\x15GetLoanProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x18ListLoanProductsResponse\x129\n" +
	"\bproducts\x18\x01 \x03(\v2\x1d.api.reference.v1.LoanProductR\bproducts\"L\n" +
	"\x14ListBranchesResponse\x124\n" +
	"\bbranches\x18\x01 \x03(\v2\x18.api.reference.v1.BranchR\bbranches\":\n" +
	"\x17ListLoanOfficersRequest\x12\x1f\n" +
	"\vbranch_code\x18\x01 \x01(\tR\n" +
	"branchCode\"U\n" +
	"\x18ListLoanOfficersResponse\x129\n" +
	"\bofficers\x18\x01 \x03(\v2\x1d.api.reference.v1.LoanOfficerR\bofficers\"e\n" +
	"\x1fListApplicationStatusesResponse\x12B\n" +
	"\bstatuses\x18\x01 \x03(\v2&.api.reference.v1.ApplicationStatusRefR\bstatuses\"d\n" +
	"\x1dListAttributeRegistryResponse\x12C\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2#.api.reference.v1.AttributeRegistryR\n" +
	"attributes\"X\n" +
	"\x1aListSurveyTemplatesRequest\x12\x1b\n" +
	"\thead_type\x18\x01 \x01(\tR\bheadType\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\"]\n" +
	"\x1bListSurveyTemplatesResponse\x12>\n" +
	"\ttemplates\x18\x01 \x03(\v2 .api.reference.v1.SurveyTemplateR\ttemplates\"c\n" +
	"\x1fListFinancialGLAccountsResponse\x12@\n" +
	"\baccounts\x18\x01 \x03(\v2$.api.reference.v1.FinancialGLAccountR\baccounts2\xee\b\n" +
	"\x10ReferenceService\x12{\n" +
	"\x10ListLoanProducts\x12\x16.google.protobuf.Empty\x1a*.api.reference.v1.ListLoanProductsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/reference/loan-products\x12\x82\x01\n" +
	"\x0eGetLoanProduct\x12'.api.reference.v1.GetLoanProductRequest\x1a\x1d.api.reference.v1.LoanProduct\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/reference/loan-products/{id}\x12n\n" +
	"\fListBranches\x12\x16.google.protobuf.Empty\x1a&.api.reference.v1.ListBranchesResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/reference/branches\x12\xa0\x01\n" +
	"\x10ListLoanOfficers\x12).api.reference.v1.ListLoanOfficersRequest\x1a*.api.reference.v1.ListLoanOfficersResponse\"5\x82\xd3\xe4\x93\x02/\x12-/v1/reference/branches/{branch_code}/officers\x12\x90\x01\n" +
	"\x17ListApplicationStatuses\x12\x16.google.protobuf.Empty\x1a1.api.reference.v1.ListApplicationStatusesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/reference/application-statuses\x12\x8a\x01\n" +
	"\x15ListAttributeRegistry\x12\x16.google.protobuf.Empty\x1a/.api.reference.v1.ListAttributeRegistryResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/reference/attribute-registry\x12\x9a\x01\n" +
	"\x13ListSurveyTemplates\x12,.api.reference.v1.ListSurveyTemplatesRequest\x1a-.api.reference.v1.ListSurveyTemplatesResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/reference/survey-templates\x12\x87\x01\n" +
	"\x17ListFinancialGLAccounts\x12\x16.google.protobuf.Empty\x1a1.api.reference.v1.ListFinancialGLAccountsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/reference/gl-accountsBB\n" +
	"\x10api.reference.v1P\x01Z,credit-analytics-backend/api/reference/v1;v1b\x06proto3"

var (
	file_reference_v1_reference_proto_rawDescOnce sync.Once
	file_reference_v1_reference_proto_rawDescData []byte
)

func file_reference_v1_reference_proto_rawDescGZIP() []byte {
	file_reference_v1_reference_proto_rawDescOnce.Do(func() {
		file_reference_v1_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reference_v1_reference_proto_rawDesc), len(file_reference_v1_reference_proto_rawDesc)))
	})
	return file_reference_v1_reference_proto_rawDescData
}

var file_reference_v1_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_reference_v1_reference_proto_goTypes = []any{
	(*LoanProduct)(nil),                     // 0: api.reference.v1.LoanProduct
	(*Branch)(nil),                          // 1: api.reference.v1.Branch
	(*LoanOfficer)(nil),                     // 2: api.reference.v1.LoanOfficer
	(*ApplicationStatusRef)(nil),            // 3: api.reference.v1.ApplicationStatusRef
	(*AttributeRegistry)(nil),               // 4: api.reference.v1.AttributeRegistry
	(*SurveyTemplate)(nil),                  // 5: api.reference.v1.SurveyTemplate
	(*FinancialGLAccount)(nil),              // 6: api.reference.v1.FinancialGLAccount
	(*GetLoanProductRequest)(nil),           // 7: api.reference.v1.GetLoanProductRequest
	(*ListLoanProductsResponse)(nil),        // 8: api.reference.v1.ListLoanProductsResponse
	(*ListBranchesResponse)(nil),            // 9: api.reference.v1.ListBranchesResponse
	(*ListLoanOfficersRequest)(nil),         // 10: api.reference.v1.ListLoanOfficersRequest
	(*ListLoanOfficersResponse)(nil),        // 11: api.reference.v1.ListLoanOfficersResponse
	(*ListApplicationStatusesResponse)(nil), // 12: api.reference.v1.ListApplicationStatusesResponse
	(*ListAttributeRegistryResponse)(nil),   // 13: api.reference.v1.ListAttributeRegistryResponse
	(*ListSurveyTemplatesRequest)(nil),      // 14: api.reference.v1.ListSurveyTemplatesRequest
	(*ListSurveyTemplatesResponse)(nil),     // 15: api.reference.v1.ListSurveyTemplatesResponse
	(*ListFinancialGLAccountsResponse)(nil), // 16: api.reference.v1.ListFinancialGLAccountsResponse
	(*emptypb.Empty)(nil),                   // 17: google.protobuf.Empty
}
var file_reference_v1_reference_proto_depIdxs = []int32{
	0,  // 0: api.reference.v1.ListLoanProductsResponse.products:type_name -> api.reference.v1.LoanProduct
	1,  // 1: api.reference.v1.ListBranchesResponse.branches:type_name -> api.reference.v1.Branch
	2,  // 2: api.reference.v1.ListLoanOfficersResponse.officers:type_name -> api.reference.v1.LoanOfficer
	3,  // 3: api.reference.v1.ListApplicationStatusesResponse.statuses:type_name -> api.reference.v1.ApplicationStatusRef
	4,  // 4: api.reference.v1.ListAttributeRegistryResponse.attributes:type_name -> api.reference.v1.AttributeRegistry
	5,  // 5: api.reference.v1.ListSurveyTemplatesResponse.templates:type_name -> api.reference.v1.SurveyTemplate
	6,  // 6: api.reference.v1.ListFinancialGLAccountsResponse.accounts:type_name -> api.reference.v1.FinancialGLAccount
	17, // 7: api.reference.v1.ReferenceService.ListLoanProducts:input_type -> google.protobuf.Empty
	7,  // 8: api.reference.v1.ReferenceService.GetLoanProduct:input_type -> api.reference.v1.GetLoanProductRequest
	17, // 9: api.reference.v1.ReferenceService.ListBranches:input_type -> google.protobuf.Empty
	10, // 10: api.reference.v1.ReferenceService.ListLoanOfficers:input_type -> api.reference.v1.ListLoanOfficersRequest
	17, // 11: api.reference.v1.ReferenceService.ListApplicationStatuses:input_type -> google.protobuf.Empty
	17, // 12: api.reference.v1.ReferenceService.ListAttributeRegistry:input_type -> google.protobuf.Empty
	14, // 13: api.reference.v1.ReferenceService.ListSurveyTemplates:input_type -> api.reference.v1.ListSurveyTemplatesRequest
	17, // 14: api.reference.v1.ReferenceService.ListFinancialGLAccounts:input_type -> google.protobuf.Empty
	8,  // 15: api.reference.v1.ReferenceService.ListLoanProducts:output_type -> api.reference.v1.ListLoanProductsResponse
	0,  // 16: api.reference.v1.ReferenceService.GetLoanProduct:output_type -> api.reference.v1.LoanProduct
	9,  // 17: api.reference.v1.ReferenceService.ListBranches:output_type -> api.reference.v1.ListBranchesResponse
	11, // 18: api.reference.v1.ReferenceService.ListLoanOfficers:output_type -> api.reference.v1.ListLoanOfficersResponse
	12, // 19: api.reference.v1.ReferenceService.ListApplicationStatuses:output_type -> api.reference.v1.ListApplicationStatusesResponse
	13, // 20: api.reference.v1.ReferenceService.ListAttributeRegistry:output_type -> api.reference.v1.ListAttributeRegistryResponse
	15, // 21: api.reference.v1.ReferenceService.ListSurveyTemplates:output_type -> api.reference.v1.ListSurveyTemplatesResponse
	16, // 22: api.reference.v1.ReferenceService.ListFinancialGLAccounts:output_type -> api.reference.v1.ListFinancialGLAccountsResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_reference_v1_reference_proto_init() }
func file_reference_v1_reference_proto_init() {
	if File_reference_v1_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reference_v1_reference_proto_rawDesc), len(file_reference_v1_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reference_v1_reference_proto_goTypes,
		DependencyIndexes: file_reference_v1_reference_proto_depIdxs,
		MessageInfos:      file_reference_v1_reference_proto_msgTypes,
	}.Build()
	File_reference_v1_reference_proto = out.File
	file_reference_v1_reference_proto_goTypes = nil
	file_reference_v1_reference_proto_depIdxs = nil
}
