// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: survey/v1/survey.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SurveyTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateCode  string                 `protobuf:"bytes,2,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	TemplateName  string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	HeadType      string                 `protobuf:"bytes,4,opt,name=head_type,json=headType,proto3" json:"head_type,omitempty"`
	ProductId     string                 `protobuf:"bytes,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyTemplate) Reset() {
	*x = SurveyTemplate{}
	mi := &file_survey_v1_survey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyTemplate) ProtoMessage() {}

func (x *SurveyTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyTemplate.ProtoReflect.Descriptor instead.
func (*SurveyTemplate) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{0}
}

func (x *SurveyTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SurveyTemplate) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SurveyTemplate) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *SurveyTemplate) GetHeadType() string {
	if x != nil {
		return x.HeadType
	}
	return ""
}

func (x *SurveyTemplate) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SurveyTemplate) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ApplicationSurvey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	SurveyType    string                 `protobuf:"bytes,4,opt,name=survey_type,json=surveyType,proto3" json:"survey_type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,6,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	SurveyPurpose string                 `protobuf:"bytes,7,opt,name=survey_purpose,json=surveyPurpose,proto3" json:"survey_purpose,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	SubmittedBy   string                 `protobuf:"bytes,10,opt,name=submitted_by,json=submittedBy,proto3" json:"submitted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationSurvey) Reset() {
	*x = ApplicationSurvey{}
	mi := &file_survey_v1_survey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationSurvey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationSurvey) ProtoMessage() {}

func (x *ApplicationSurvey) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationSurvey.ProtoReflect.Descriptor instead.
func (*ApplicationSurvey) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationSurvey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationSurvey) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApplicationSurvey) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ApplicationSurvey) GetSurveyType() string {
	if x != nil {
		return x.SurveyType
	}
	return ""
}

func (x *ApplicationSurvey) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApplicationSurvey) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *ApplicationSurvey) GetSurveyPurpose() string {
	if x != nil {
		return x.SurveyPurpose
	}
	return ""
}

func (x *ApplicationSurvey) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ApplicationSurvey) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *ApplicationSurvey) GetSubmittedBy() string {
	if x != nil {
		return x.SubmittedBy
	}
	return ""
}

type SurveyAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SurveyId      string                 `protobuf:"bytes,2,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	QuestionId    string                 `protobuf:"bytes,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerText    string                 `protobuf:"bytes,4,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	AnswerNumber  string                 `protobuf:"bytes,5,opt,name=answer_number,json=answerNumber,proto3" json:"answer_number,omitempty"`
	AnswerBoolean bool                   `protobuf:"varint,6,opt,name=answer_boolean,json=answerBoolean,proto3" json:"answer_boolean,omitempty"`
	AnswerDate    string                 `protobuf:"bytes,7,opt,name=answer_date,json=answerDate,proto3" json:"answer_date,omitempty"`
	AnsweredAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=answered_at,json=answeredAt,proto3" json:"answered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyAnswer) Reset() {
	*x = SurveyAnswer{}
	mi := &file_survey_v1_survey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyAnswer) ProtoMessage() {}

func (x *SurveyAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyAnswer.ProtoReflect.Descriptor instead.
func (*SurveyAnswer) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{2}
}

func (x *SurveyAnswer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SurveyAnswer) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

func (x *SurveyAnswer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SurveyAnswer) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *SurveyAnswer) GetAnswerNumber() string {
	if x != nil {
		return x.AnswerNumber
	}
	return ""
}

func (x *SurveyAnswer) GetAnswerBoolean() bool {
	if x != nil {
		return x.AnswerBoolean
	}
	return false
}

func (x *SurveyAnswer) GetAnswerDate() string {
	if x != nil {
		return x.AnswerDate
	}
	return ""
}

func (x *SurveyAnswer) GetAnsweredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnsweredAt
	}
	return nil
}

type SurveyEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SurveyId      string                 `protobuf:"bytes,2,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	EvidenceType  string                 `protobuf:"bytes,3,opt,name=evidence_type,json=evidenceType,proto3" json:"evidence_type,omitempty"`
	FileUrl       string                 `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CapturedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyEvidence) Reset() {
	*x = SurveyEvidence{}
	mi := &file_survey_v1_survey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyEvidence) ProtoMessage() {}

func (x *SurveyEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyEvidence.ProtoReflect.Descriptor instead.
func (*SurveyEvidence) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{3}
}

func (x *SurveyEvidence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SurveyEvidence) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

func (x *SurveyEvidence) GetEvidenceType() string {
	if x != nil {
		return x.EvidenceType
	}
	return ""
}

func (x *SurveyEvidence) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *SurveyEvidence) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SurveyEvidence) GetCapturedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CapturedAt
	}
	return nil
}

type ListSurveysByApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSurveysByApplicationRequest) Reset() {
	*x = ListSurveysByApplicationRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSurveysByApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSurveysByApplicationRequest) ProtoMessage() {}

func (x *ListSurveysByApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSurveysByApplicationRequest.ProtoReflect.Descriptor instead.
func (*ListSurveysByApplicationRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{4}
}

func (x *ListSurveysByApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListSurveysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Surveys       []*ApplicationSurvey   `protobuf:"bytes,1,rep,name=surveys,proto3" json:"surveys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSurveysResponse) Reset() {
	*x = ListSurveysResponse{}
	mi := &file_survey_v1_survey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSurveysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSurveysResponse) ProtoMessage() {}

func (x *ListSurveysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSurveysResponse.ProtoReflect.Descriptor instead.
func (*ListSurveysResponse) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{5}
}

func (x *ListSurveysResponse) GetSurveys() []*ApplicationSurvey {
	if x != nil {
		return x.Surveys
	}
	return nil
}

type StartSurveyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSurveyRequest) Reset() {
	*x = StartSurveyRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSurveyRequest) ProtoMessage() {}

func (x *StartSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSurveyRequest.ProtoReflect.Descriptor instead.
func (*StartSurveyRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{6}
}

func (x *StartSurveyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartSurveyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SubmitSurveyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSurveyRequest) Reset() {
	*x = SubmitSurveyRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSurveyRequest) ProtoMessage() {}

func (x *SubmitSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSurveyRequest.ProtoReflect.Descriptor instead.
func (*SubmitSurveyRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitSurveyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubmitSurveyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type VerifySurveyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifySurveyRequest) Reset() {
	*x = VerifySurveyRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifySurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySurveyRequest) ProtoMessage() {}

func (x *VerifySurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySurveyRequest.ProtoReflect.Descriptor instead.
func (*VerifySurveyRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{8}
}

func (x *VerifySurveyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerifySurveyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SubmitSurveyAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SurveyId      string                 `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerText    string                 `protobuf:"bytes,3,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	AnswerNumber  string                 `protobuf:"bytes,4,opt,name=answer_number,json=answerNumber,proto3" json:"answer_number,omitempty"`
	AnswerBoolean bool                   `protobuf:"varint,5,opt,name=answer_boolean,json=answerBoolean,proto3" json:"answer_boolean,omitempty"`
	AnswerDate    string                 `protobuf:"bytes,6,opt,name=answer_date,json=answerDate,proto3" json:"answer_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSurveyAnswerRequest) Reset() {
	*x = SubmitSurveyAnswerRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSurveyAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSurveyAnswerRequest) ProtoMessage() {}

func (x *SubmitSurveyAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSurveyAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitSurveyAnswerRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitSurveyAnswerRequest) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

func (x *SubmitSurveyAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *SubmitSurveyAnswerRequest) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *SubmitSurveyAnswerRequest) GetAnswerNumber() string {
	if x != nil {
		return x.AnswerNumber
	}
	return ""
}

func (x *SubmitSurveyAnswerRequest) GetAnswerBoolean() bool {
	if x != nil {
		return x.AnswerBoolean
	}
	return false
}

func (x *SubmitSurveyAnswerRequest) GetAnswerDate() string {
	if x != nil {
		return x.AnswerDate
	}
	return ""
}

type UploadSurveyEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SurveyId      string                 `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	EvidenceType  string                 `protobuf:"bytes,2,opt,name=evidence_type,json=evidenceType,proto3" json:"evidence_type,omitempty"`
	FileUrl       string                 `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSurveyEvidenceRequest) Reset() {
	*x = UploadSurveyEvidenceRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSurveyEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSurveyEvidenceRequest) ProtoMessage() {}

func (x *UploadSurveyEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSurveyEvidenceRequest.ProtoReflect.Descriptor instead.
func (*UploadSurveyEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{10}
}

func (x *UploadSurveyEvidenceRequest) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

func (x *UploadSurveyEvidenceRequest) GetEvidenceType() string {
	if x != nil {
		return x.EvidenceType
	}
	return ""
}

func (x *UploadSurveyEvidenceRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UploadSurveyEvidenceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AssignSurveyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	SurveyType    string                 `protobuf:"bytes,3,opt,name=survey_type,json=surveyType,proto3" json:"survey_type,omitempty"`
	AssignedTo    string                 `protobuf:"bytes,4,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	SurveyPurpose string                 `protobuf:"bytes,5,opt,name=survey_purpose,json=surveyPurpose,proto3" json:"survey_purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignSurveyRequest) Reset() {
	*x = AssignSurveyRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignSurveyRequest) ProtoMessage() {}

func (x *AssignSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignSurveyRequest.ProtoReflect.Descriptor instead.
func (*AssignSurveyRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{11}
}

func (x *AssignSurveyRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *AssignSurveyRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *AssignSurveyRequest) GetSurveyType() string {
	if x != nil {
		return x.SurveyType
	}
	return ""
}

func (x *AssignSurveyRequest) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *AssignSurveyRequest) GetSurveyPurpose() string {
	if x != nil {
		return x.SurveyPurpose
	}
	return ""
}

type GetSurveyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSurveyRequest) Reset() {
	*x = GetSurveyRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurveyRequest) ProtoMessage() {}

func (x *GetSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurveyRequest.ProtoReflect.Descriptor instead.
func (*GetSurveyRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{12}
}

func (x *GetSurveyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateSurveyTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateCode  string                 `protobuf:"bytes,1,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	TemplateName  string                 `protobuf:"bytes,2,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	HeadType      string                 `protobuf:"bytes,3,opt,name=head_type,json=headType,proto3" json:"head_type,omitempty"`
	ProductId     string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSurveyTemplateRequest) Reset() {
	*x = CreateSurveyTemplateRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSurveyTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSurveyTemplateRequest) ProtoMessage() {}

func (x *CreateSurveyTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSurveyTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateSurveyTemplateRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSurveyTemplateRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *CreateSurveyTemplateRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *CreateSurveyTemplateRequest) GetHeadType() string {
	if x != nil {
		return x.HeadType
	}
	return ""
}

func (x *CreateSurveyTemplateRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateSurveyTemplateRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ListSurveyTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSurveyTemplatesRequest) Reset() {
	*x = ListSurveyTemplatesRequest{}
	mi := &file_survey_v1_survey_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSurveyTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSurveyTemplatesRequest) ProtoMessage() {}

func (x *ListSurveyTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSurveyTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListSurveyTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{14}
}

type ListSurveyTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*SurveyTemplate      `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSurveyTemplatesResponse) Reset() {
	*x = ListSurveyTemplatesResponse{}
	mi := &file_survey_v1_survey_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSurveyTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSurveyTemplatesResponse) ProtoMessage() {}

func (x *ListSurveyTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_survey_v1_survey_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSurveyTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListSurveyTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_survey_v1_survey_proto_rawDescGZIP(), []int{15}
}

func (x *ListSurveyTemplatesResponse) GetTemplates() []*SurveyTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

var File_survey_v1_survey_proto protoreflect.FileDescriptor

const file_survey_v1_survey_proto_rawDesc = "" +
	"\n" +
	"\x16survey/v1/survey.proto\x12\rapi.survey.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n" +
	"\x0eSurveyTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rtemplate_code\x18\x02 \x01(\tR\ftemplateCode\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12\x1b\n" +
	"\thead_type\x18\x04 \x01(\tR\bheadType\x12\x1d\n" +
	"\n" +
	"product_id\x18\x05 \x01(\tR\tproductId\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"\x89\x03\n" +
	"\x11ApplicationSurvey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12\x1f\n" +
	"\vsurvey_type\x18\x04 \x01(\tR\n" +
	"surveyType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vassigned_to\x18\x06 \x01(\tR\n" +
	"assignedTo\x12%\n" +
	"\x0esurvey_purpose\x18\a \x01(\tR\rsurveyPurpose\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fsubmitted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12!\n" +
	"\fsubmitted_by\x18\n" +
	" \x01(\tR\vsubmittedBy\"\xa7\x02\n" +
	"\fSurveyAnswer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsurvey_id\x18\x02 \x01(\tR\bsurveyId\x12\x1f\n" +
	"\vquestion_id\x18\x03 \x01(\tR\n" +
	"questionId\x12\x1f\n" +
	"\vanswer_text\x18\x04 \x01(\tR\n" +
	"answerText\x12#\n" +
	"\ranswer_number\x18\x05 \x01(\tR\fanswerNumber\x12%\n" +
	"\x0eanswer_boolean\x18\x06 \x01(\bR\ranswerBoolean\x12\x1f\n" +
	"\vanswer_date\x18\a \x01(\tR\n" +
	"answerDate\x12;\n" +
	"\vanswered_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"answeredAt\"\xdc\x01\n" +
	"\x0eSurveyEvidence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsurvey_id\x18\x02 \x01(\tR\bsurveyId\x12#\n" +
	"\revidence_type\x18\x03 \x01(\tR\fevidenceType\x12\x19\n" +
	"\bfile_url\x18\x04 \x01(\tR\afileUrl\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12;\n" +
	"\vcaptured_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"capturedAt\"H\n" +
	"\x1fListSurveysByApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"Q\n" +
	"\x13ListSurveysResponse\x12:\n" +
	"\asurveys\x18\x01 \x03(\v2 .api.survey.v1.ApplicationSurveyR\asurveys\"=\n" +
	"\x12StartSurveyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\">\n" +
	"\x13SubmitSurveyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\">\n" +
	"\x13VerifySurveyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xe7\x01\n" +
	"\x19SubmitSurveyAnswerRequest\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\x12\x1f\n" +
	"\vanswer_text\x18\x03 \x01(\tR\n" +
	"answerText\x12#\n" +
	"\ranswer_number\x18\x04 \x01(\tR\fanswerNumber\x12%\n" +
	"\x0eanswer_boolean\x18\x05 \x01(\bR\ranswerBoolean\x12\x1f\n" +
	"\vanswer_date\x18\x06 \x01(\tR\n" +
	"answerDate\"\x9c\x01\n" +
	"\x1bUploadSurveyEvidenceRequest\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\x12#\n" +
	"\revidence_type\x18\x02 \x01(\tR\fevidenceType\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xc6\x01\n" +
	"\x13AssignSurveyRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x1f\n" +
	"\vsurvey_type\x18\x03 \x01(\tR\n" +
	"surveyType\x12\x1f\n" +
	"\vassigned_to\x18\x04 \x01(\tR\n" +
	"assignedTo\x12%\n" +
	"\x0esurvey_purpose\x18\x05 \x01(\tR\rsurveyPurpose\"\"\n" +
	"\x10GetSurveyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbb\x01\n" +
	"\x1bCreateSurveyTemplateRequest\x12#\n" +
	"\rtemplate_code\x18\x01 \x01(\tR\ftemplateCode\x12#\n" +
	"\rtemplate_name\x18\x02 \x01(\tR\ftemplateName\x12\x1b\n" +
	"\thead_type\x18\x03 \x01(\tR\bheadType\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\"\x1c\n" +
	"\x1aListSurveyTemplatesRequest\"Z\n" +
	"\x1bListSurveyTemplatesResponse\x12;\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1d.api.survey.v1.SurveyTemplateR\ttemplates2\xb1\b\n" +
	"\rSurveyService\x12\x8a\x01\n" +
	"\fAssignSurvey\x12\".api.survey.v1.AssignSurveyRequest\x1a .api.survey.v1.ApplicationSurvey\"4\x82\xd3\xe4\x93\x02.:\x01*\")/v1/applications/{application_id}/surveys\x12h\n" +
	"\tGetSurvey\x12\x1f.api.survey.v1.GetSurveyRequest\x1a .api.survey.v1.ApplicationSurvey\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/surveys/{id}\x12\xa1\x01\n" +
	"\x18ListSurveysByApplication\x12..api.survey.v1.ListSurveysByApplicationRequest\x1a\".api.survey.v1.ListSurveysResponse\"1\x82\xd3\xe4\x93\x02+\x12)/v1/applications/{application_id}/surveys\x12u\n" +
	"\vStartSurvey\x12!.api.survey.v1.StartSurveyRequest\x1a .api.survey.v1.ApplicationSurvey\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/surveys/{id}/start\x12x\n" +
	"\fSubmitSurvey\x12\".api.survey.v1.SubmitSurveyRequest\x1a .api.survey.v1.ApplicationSurvey\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/surveys/{id}/submit\x12x\n" +
	"\fVerifySurvey\x12\".api.survey.v1.VerifySurveyRequest\x1a .api.survey.v1.ApplicationSurvey\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/surveys/{id}/verify\x12\x87\x01\n" +
	"\x12SubmitSurveyAnswer\x12(.api.survey.v1.SubmitSurveyAnswerRequest\x1a\x1b.api.survey.v1.SurveyAnswer\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/surveys/{survey_id}/answers\x12\x8f\x01\n" +
	"\x14UploadSurveyEvidence\x12*.api.survey.v1.UploadSurveyEvidenceRequest\x1a\x1d.api.survey.v1.SurveyEvidence\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/surveys/{survey_id}/evidencesB<\n" +
	"\rapi.survey.v1P\x01Z)credit-analytics-backend/api/survey/v1;v1b\x06proto3"

var (
	file_survey_v1_survey_proto_rawDescOnce sync.Once
	file_survey_v1_survey_proto_rawDescData []byte
)

func file_survey_v1_survey_proto_rawDescGZIP() []byte {
	file_survey_v1_survey_proto_rawDescOnce.Do(func() {
		file_survey_v1_survey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_survey_v1_survey_proto_rawDesc), len(file_survey_v1_survey_proto_rawDesc)))
	})
	return file_survey_v1_survey_proto_rawDescData
}

var file_survey_v1_survey_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_survey_v1_survey_proto_goTypes = []any{
	(*SurveyTemplate)(nil),                  // 0: api.survey.v1.SurveyTemplate
	(*ApplicationSurvey)(nil),               // 1: api.survey.v1.ApplicationSurvey
	(*SurveyAnswer)(nil),                    // 2: api.survey.v1.SurveyAnswer
	(*SurveyEvidence)(nil),                  // 3: api.survey.v1.SurveyEvidence
	(*ListSurveysByApplicationRequest)(nil), // 4: api.survey.v1.ListSurveysByApplicationRequest
	(*ListSurveysResponse)(nil),             // 5: api.survey.v1.ListSurveysResponse
	(*StartSurveyRequest)(nil),              // 6: api.survey.v1.StartSurveyRequest
	(*SubmitSurveyRequest)(nil),             // 7: api.survey.v1.SubmitSurveyRequest
	(*VerifySurveyRequest)(nil),             // 8: api.survey.v1.VerifySurveyRequest
	(*SubmitSurveyAnswerRequest)(nil),       // 9: api.survey.v1.SubmitSurveyAnswerRequest
	(*UploadSurveyEvidenceRequest)(nil),     // 10: api.survey.v1.UploadSurveyEvidenceRequest
	(*AssignSurveyRequest)(nil),             // 11: api.survey.v1.AssignSurveyRequest
	(*GetSurveyRequest)(nil),                // 12: api.survey.v1.GetSurveyRequest
	(*CreateSurveyTemplateRequest)(nil),     // 13: api.survey.v1.CreateSurveyTemplateRequest
	(*ListSurveyTemplatesRequest)(nil),      // 14: api.survey.v1.ListSurveyTemplatesRequest
	(*ListSurveyTemplatesResponse)(nil),     // 15: api.survey.v1.ListSurveyTemplatesResponse
	(*timestamppb.Timestamp)(nil),           // 16: google.protobuf.Timestamp
}
var file_survey_v1_survey_proto_depIdxs = []int32{
	16, // 0: api.survey.v1.ApplicationSurvey.started_at:type_name -> google.protobuf.Timestamp
	16, // 1: api.survey.v1.ApplicationSurvey.submitted_at:type_name -> google.protobuf.Timestamp
	16, // 2: api.survey.v1.SurveyAnswer.answered_at:type_name -> google.protobuf.Timestamp
	16, // 3: api.survey.v1.SurveyEvidence.captured_at:type_name -> google.protobuf.Timestamp
	1,  // 4: api.survey.v1.ListSurveysResponse.surveys:type_name -> api.survey.v1.ApplicationSurvey
	0,  // 5: api.survey.v1.ListSurveyTemplatesResponse.templates:type_name -> api.survey.v1.SurveyTemplate
	11, // 6: api.survey.v1.SurveyService.AssignSurvey:input_type -> api.survey.v1.AssignSurveyRequest
	12, // 7: api.survey.v1.SurveyService.GetSurvey:input_type -> api.survey.v1.GetSurveyRequest
	4,  // 8: api.survey.v1.SurveyService.ListSurveysByApplication:input_type -> api.survey.v1.ListSurveysByApplicationRequest
	6,  // 9: api.survey.v1.SurveyService.StartSurvey:input_type -> api.survey.v1.StartSurveyRequest
	7,  // 10: api.survey.v1.SurveyService.SubmitSurvey:input_type -> api.survey.v1.SubmitSurveyRequest
	8,  // 11: api.survey.v1.SurveyService.VerifySurvey:input_type -> api.survey.v1.VerifySurveyRequest
	9,  // 12: api.survey.v1.SurveyService.SubmitSurveyAnswer:input_type -> api.survey.v1.SubmitSurveyAnswerRequest
	10, // 13: api.survey.v1.SurveyService.UploadSurveyEvidence:input_type -> api.survey.v1.UploadSurveyEvidenceRequest
	1,  // 14: api.survey.v1.SurveyService.AssignSurvey:output_type -> api.survey.v1.ApplicationSurvey
	1,  // 15: api.survey.v1.SurveyService.GetSurvey:output_type -> api.survey.v1.ApplicationSurvey
	5,  // 16: api.survey.v1.SurveyService.ListSurveysByApplication:output_type -> api.survey.v1.ListSurveysResponse
	1,  // 17: api.survey.v1.SurveyService.StartSurvey:output_type -> api.survey.v1.ApplicationSurvey
	1,  // 18: api.survey.v1.SurveyService.SubmitSurvey:output_type -> api.survey.v1.ApplicationSurvey
	1,  // 19: api.survey.v1.SurveyService.VerifySurvey:output_type -> api.survey.v1.ApplicationSurvey
	2,  // 20: api.survey.v1.SurveyService.SubmitSurveyAnswer:output_type -> api.survey.v1.SurveyAnswer
	3,  // 21: api.survey.v1.SurveyService.UploadSurveyEvidence:output_type -> api.survey.v1.SurveyEvidence
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_survey_v1_survey_proto_init() }
func file_survey_v1_survey_proto_init() {
	if File_survey_v1_survey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_survey_v1_survey_proto_rawDesc), len(file_survey_v1_survey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_survey_v1_survey_proto_goTypes,
		DependencyIndexes: file_survey_v1_survey_proto_depIdxs,
		MessageInfos:      file_survey_v1_survey_proto_msgTypes,
	}.Build()
	File_survey_v1_survey_proto = out.File
	file_survey_v1_survey_proto_goTypes = nil
	file_survey_v1_survey_proto_depIdxs = nil
}
