// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: financial/v1/financial.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationFinancialFact struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	GlCode          string                 `protobuf:"bytes,3,opt,name=gl_code,json=glCode,proto3" json:"gl_code,omitempty"`
	PeriodType      string                 `protobuf:"bytes,4,opt,name=period_type,json=periodType,proto3" json:"period_type,omitempty"`
	PeriodLabel     string                 `protobuf:"bytes,5,opt,name=period_label,json=periodLabel,proto3" json:"period_label,omitempty"`
	Amount          string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Source          string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	ConfidenceLevel string                 `protobuf:"bytes,8,opt,name=confidence_level,json=confidenceLevel,proto3" json:"confidence_level,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplicationFinancialFact) Reset() {
	*x = ApplicationFinancialFact{}
	mi := &file_financial_v1_financial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationFinancialFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationFinancialFact) ProtoMessage() {}

func (x *ApplicationFinancialFact) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationFinancialFact.ProtoReflect.Descriptor instead.
func (*ApplicationFinancialFact) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationFinancialFact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationFinancialFact) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApplicationFinancialFact) GetGlCode() string {
	if x != nil {
		return x.GlCode
	}
	return ""
}

func (x *ApplicationFinancialFact) GetPeriodType() string {
	if x != nil {
		return x.PeriodType
	}
	return ""
}

func (x *ApplicationFinancialFact) GetPeriodLabel() string {
	if x != nil {
		return x.PeriodLabel
	}
	return ""
}

func (x *ApplicationFinancialFact) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ApplicationFinancialFact) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ApplicationFinancialFact) GetConfidenceLevel() string {
	if x != nil {
		return x.ConfidenceLevel
	}
	return ""
}

func (x *ApplicationFinancialFact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ApplicationAsset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	AssetTypeCode   string                 `protobuf:"bytes,3,opt,name=asset_type_code,json=assetTypeCode,proto3" json:"asset_type_code,omitempty"`
	AssetName       string                 `protobuf:"bytes,4,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	OwnershipStatus string                 `protobuf:"bytes,5,opt,name=ownership_status,json=ownershipStatus,proto3" json:"ownership_status,omitempty"`
	AcquisitionYear int32                  `protobuf:"varint,6,opt,name=acquisition_year,json=acquisitionYear,proto3" json:"acquisition_year,omitempty"`
	EstimatedValue  string                 `protobuf:"bytes,7,opt,name=estimated_value,json=estimatedValue,proto3" json:"estimated_value,omitempty"`
	ValuationMethod string                 `protobuf:"bytes,8,opt,name=valuation_method,json=valuationMethod,proto3" json:"valuation_method,omitempty"`
	LocationText    string                 `protobuf:"bytes,9,opt,name=location_text,json=locationText,proto3" json:"location_text,omitempty"`
	Encumbered      bool                   `protobuf:"varint,10,opt,name=encumbered,proto3" json:"encumbered,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplicationAsset) Reset() {
	*x = ApplicationAsset{}
	mi := &file_financial_v1_financial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationAsset) ProtoMessage() {}

func (x *ApplicationAsset) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationAsset.ProtoReflect.Descriptor instead.
func (*ApplicationAsset) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationAsset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationAsset) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApplicationAsset) GetAssetTypeCode() string {
	if x != nil {
		return x.AssetTypeCode
	}
	return ""
}

func (x *ApplicationAsset) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *ApplicationAsset) GetOwnershipStatus() string {
	if x != nil {
		return x.OwnershipStatus
	}
	return ""
}

func (x *ApplicationAsset) GetAcquisitionYear() int32 {
	if x != nil {
		return x.AcquisitionYear
	}
	return 0
}

func (x *ApplicationAsset) GetEstimatedValue() string {
	if x != nil {
		return x.EstimatedValue
	}
	return ""
}

func (x *ApplicationAsset) GetValuationMethod() string {
	if x != nil {
		return x.ValuationMethod
	}
	return ""
}

func (x *ApplicationAsset) GetLocationText() string {
	if x != nil {
		return x.LocationText
	}
	return ""
}

func (x *ApplicationAsset) GetEncumbered() bool {
	if x != nil {
		return x.Encumbered
	}
	return false
}

type ApplicationLiability struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId      string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	CreditorName       string                 `protobuf:"bytes,3,opt,name=creditor_name,json=creditorName,proto3" json:"creditor_name,omitempty"`
	LiabilityType      string                 `protobuf:"bytes,4,opt,name=liability_type,json=liabilityType,proto3" json:"liability_type,omitempty"`
	OutstandingAmount  string                 `protobuf:"bytes,5,opt,name=outstanding_amount,json=outstandingAmount,proto3" json:"outstanding_amount,omitempty"`
	MonthlyInstallment string                 `protobuf:"bytes,6,opt,name=monthly_installment,json=monthlyInstallment,proto3" json:"monthly_installment,omitempty"`
	InterestRate       string                 `protobuf:"bytes,7,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	MaturityDate       string                 `protobuf:"bytes,8,opt,name=maturity_date,json=maturityDate,proto3" json:"maturity_date,omitempty"`
	Source             string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplicationLiability) Reset() {
	*x = ApplicationLiability{}
	mi := &file_financial_v1_financial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationLiability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationLiability) ProtoMessage() {}

func (x *ApplicationLiability) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationLiability.ProtoReflect.Descriptor instead.
func (*ApplicationLiability) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationLiability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplicationLiability) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApplicationLiability) GetCreditorName() string {
	if x != nil {
		return x.CreditorName
	}
	return ""
}

func (x *ApplicationLiability) GetLiabilityType() string {
	if x != nil {
		return x.LiabilityType
	}
	return ""
}

func (x *ApplicationLiability) GetOutstandingAmount() string {
	if x != nil {
		return x.OutstandingAmount
	}
	return ""
}

func (x *ApplicationLiability) GetMonthlyInstallment() string {
	if x != nil {
		return x.MonthlyInstallment
	}
	return ""
}

func (x *ApplicationLiability) GetInterestRate() string {
	if x != nil {
		return x.InterestRate
	}
	return ""
}

func (x *ApplicationLiability) GetMaturityDate() string {
	if x != nil {
		return x.MaturityDate
	}
	return ""
}

func (x *ApplicationLiability) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type FinancialRatio struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId      string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	RatioCode          string                 `protobuf:"bytes,3,opt,name=ratio_code,json=ratioCode,proto3" json:"ratio_code,omitempty"`
	RatioValue         string                 `protobuf:"bytes,4,opt,name=ratio_value,json=ratioValue,proto3" json:"ratio_value,omitempty"`
	CalculationVersion string                 `protobuf:"bytes,5,opt,name=calculation_version,json=calculationVersion,proto3" json:"calculation_version,omitempty"`
	CalculatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=calculated_at,json=calculatedAt,proto3" json:"calculated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FinancialRatio) Reset() {
	*x = FinancialRatio{}
	mi := &file_financial_v1_financial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialRatio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialRatio) ProtoMessage() {}

func (x *FinancialRatio) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialRatio.ProtoReflect.Descriptor instead.
func (*FinancialRatio) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{3}
}

func (x *FinancialRatio) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FinancialRatio) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *FinancialRatio) GetRatioCode() string {
	if x != nil {
		return x.RatioCode
	}
	return ""
}

func (x *FinancialRatio) GetRatioValue() string {
	if x != nil {
		return x.RatioValue
	}
	return ""
}

func (x *FinancialRatio) GetCalculationVersion() string {
	if x != nil {
		return x.CalculationVersion
	}
	return ""
}

func (x *FinancialRatio) GetCalculatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculatedAt
	}
	return nil
}

type UpsertFinancialFactRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId   string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	GlCode          string                 `protobuf:"bytes,2,opt,name=gl_code,json=glCode,proto3" json:"gl_code,omitempty"`
	PeriodType      string                 `protobuf:"bytes,3,opt,name=period_type,json=periodType,proto3" json:"period_type,omitempty"`
	PeriodLabel     string                 `protobuf:"bytes,4,opt,name=period_label,json=periodLabel,proto3" json:"period_label,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Source          string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	ConfidenceLevel string                 `protobuf:"bytes,7,opt,name=confidence_level,json=confidenceLevel,proto3" json:"confidence_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpsertFinancialFactRequest) Reset() {
	*x = UpsertFinancialFactRequest{}
	mi := &file_financial_v1_financial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFinancialFactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFinancialFactRequest) ProtoMessage() {}

func (x *UpsertFinancialFactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFinancialFactRequest.ProtoReflect.Descriptor instead.
func (*UpsertFinancialFactRequest) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertFinancialFactRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetGlCode() string {
	if x != nil {
		return x.GlCode
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetPeriodType() string {
	if x != nil {
		return x.PeriodType
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetPeriodLabel() string {
	if x != nil {
		return x.PeriodLabel
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpsertFinancialFactRequest) GetConfidenceLevel() string {
	if x != nil {
		return x.ConfidenceLevel
	}
	return ""
}

type ListFinancialFactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinancialFactsRequest) Reset() {
	*x = ListFinancialFactsRequest{}
	mi := &file_financial_v1_financial_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinancialFactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinancialFactsRequest) ProtoMessage() {}

func (x *ListFinancialFactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinancialFactsRequest.ProtoReflect.Descriptor instead.
func (*ListFinancialFactsRequest) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{5}
}

func (x *ListFinancialFactsRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListFinancialFactsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Facts         []*ApplicationFinancialFact `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinancialFactsResponse) Reset() {
	*x = ListFinancialFactsResponse{}
	mi := &file_financial_v1_financial_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinancialFactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinancialFactsResponse) ProtoMessage() {}

func (x *ListFinancialFactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinancialFactsResponse.ProtoReflect.Descriptor instead.
func (*ListFinancialFactsResponse) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{6}
}

func (x *ListFinancialFactsResponse) GetFacts() []*ApplicationFinancialFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type AddAssetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId   string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	AssetTypeCode   string                 `protobuf:"bytes,2,opt,name=asset_type_code,json=assetTypeCode,proto3" json:"asset_type_code,omitempty"`
	AssetName       string                 `protobuf:"bytes,3,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	OwnershipStatus string                 `protobuf:"bytes,4,opt,name=ownership_status,json=ownershipStatus,proto3" json:"ownership_status,omitempty"`
	AcquisitionYear int32                  `protobuf:"varint,5,opt,name=acquisition_year,json=acquisitionYear,proto3" json:"acquisition_year,omitempty"`
	EstimatedValue  string                 `protobuf:"bytes,6,opt,name=estimated_value,json=estimatedValue,proto3" json:"estimated_value,omitempty"`
	ValuationMethod string                 `protobuf:"bytes,7,opt,name=valuation_method,json=valuationMethod,proto3" json:"valuation_method,omitempty"`
	LocationText    string                 `protobuf:"bytes,8,opt,name=location_text,json=locationText,proto3" json:"location_text,omitempty"`
	Encumbered      bool                   `protobuf:"varint,9,opt,name=encumbered,proto3" json:"encumbered,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddAssetRequest) Reset() {
	*x = AddAssetRequest{}
	mi := &file_financial_v1_financial_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAssetRequest) ProtoMessage() {}

func (x *AddAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAssetRequest.ProtoReflect.Descriptor instead.
func (*AddAssetRequest) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{7}
}

func (x *AddAssetRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *AddAssetRequest) GetAssetTypeCode() string {
	if x != nil {
		return x.AssetTypeCode
	}
	return ""
}

func (x *AddAssetRequest) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *AddAssetRequest) GetOwnershipStatus() string {
	if x != nil {
		return x.OwnershipStatus
	}
	return ""
}

func (x *AddAssetRequest) GetAcquisitionYear() int32 {
	if x != nil {
		return x.AcquisitionYear
	}
	return 0
}

func (x *AddAssetRequest) GetEstimatedValue() string {
	if x != nil {
		return x.EstimatedValue
	}
	return ""
}

func (x *AddAssetRequest) GetValuationMethod() string {
	if x != nil {
		return x.ValuationMethod
	}
	return ""
}

func (x *AddAssetRequest) GetLocationText() string {
	if x != nil {
		return x.LocationText
	}
	return ""
}

func (x *AddAssetRequest) GetEncumbered() bool {
	if x != nil {
		return x.Encumbered
	}
	return false
}

type UpdateAssetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	AssetTypeCode   string                 `protobuf:"bytes,3,opt,name=asset_type_code,json=assetTypeCode,proto3" json:"asset_type_code,omitempty"`
	AssetName       string                 `protobuf:"bytes,4,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	OwnershipStatus string                 `protobuf:"bytes,5,opt,name=ownership_status,json=ownershipStatus,proto3" json:"ownership_status,omitempty"`
	AcquisitionYear int32                  `protobuf:"varint,6,opt,name=acquisition_year,json=acquisitionYear,proto3" json:"acquisition_year,omitempty"`
	EstimatedValue  string                 `protobuf:"bytes,7,opt,name=estimated_value,json=estimatedValue,proto3" json:"estimated_value,omitempty"`
	ValuationMethod string                 `protobuf:"bytes,8,opt,name=valuation_method,json=valuationMethod,proto3" json:"valuation_method,omitempty"`
	LocationText    string                 `protobuf:"bytes,9,opt,name=location_text,json=locationText,proto3" json:"location_text,omitempty"`
	Encumbered      bool                   `protobuf:"varint,10,opt,name=encumbered,proto3" json:"encumbered,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateAssetRequest) Reset() {
	*x = UpdateAssetRequest{}
	mi := &file_financial_v1_financial_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetRequest) ProtoMessage() {}

func (x *UpdateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetRequest) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAssetRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UpdateAssetRequest) GetAssetTypeCode() string {
	if x != nil {
		return x.AssetTypeCode
	}
	return ""
}

func (x *UpdateAssetRequest) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *UpdateAssetRequest) GetOwnershipStatus() string {
	if x != nil {
		return x.OwnershipStatus
	}
	return ""
}

func (x *UpdateAssetRequest) GetAcquisitionYear() int32 {
	if x != nil {
		return x.AcquisitionYear
	}
	return 0
}

func (x *UpdateAssetRequest) GetEstimatedValue() string {
	if x != nil {
		return x.EstimatedValue
	}
	return ""
}

func (x *UpdateAssetRequest) GetValuationMethod() string {
	if x != nil {
		return x.ValuationMethod
	}
	return ""
}

func (x *UpdateAssetRequest) GetLocationText() string {
	if x != nil {
		return x.LocationText
	}
	return ""
}

func (x *UpdateAssetRequest) GetEncumbered() bool {
	if x != nil {
		return x.Encumbered
	}
	return false
}

type ListAssetsByApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsByApplicationRequest) Reset() {
	*x = ListAssetsByApplicationRequest{}
	mi := &file_financial_v1_financial_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsByApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsByApplicationRequest) ProtoMessage() {}

func (x *ListAssetsByApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsByApplicationRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsByApplicationRequest) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{9}
}

func (x *ListAssetsByApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*ApplicationAsset    `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_financial_v1_financial_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{10}
}

func (x *ListAssetsResponse) GetAssets() []*ApplicationAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type AddLiabilityRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId      string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	CreditorName       string                 `protobuf:"bytes,2,opt,name=creditor_name,json=creditorName,proto3" json:"creditor_name,omitempty"`
	LiabilityType      string                 `protobuf:"bytes,3,opt,name=liability_type,json=liabilityType,proto3" json:"liability_type,omitempty"`
	OutstandingAmount  string                 `protobuf:"bytes,4,opt,name=outstanding_amount,json=outstandingAmount,proto3" json:"outstanding_amount,omitempty"`
	MonthlyInstallment string                 `protobuf:"bytes,5,opt,name=monthly_installment,json=monthlyInstallment,proto3" json:"monthly_installment,omitempty"`
	InterestRate       string                 `protobuf:"bytes,6,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	MaturityDate       string                 `protobuf:"bytes,7,opt,name=maturity_date,json=maturityDate,proto3" json:"maturity_date,omitempty"`
	Source             string                 `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AddLiabilityRequest) Reset() {
	*x = AddLiabilityRequest{}
	mi := &file_financial_v1_financial_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLiabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLiabilityRequest) ProtoMessage() {}

func (x *AddLiabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLiabilityRequest.ProtoReflect.Descriptor instead.
func (*AddLiabilityRequest) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{11}
}

func (x *AddLiabilityRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *AddLiabilityRequest) GetCreditorName() string {
	if x != nil {
		return x.CreditorName
	}
	return ""
}

func (x *AddLiabilityRequest) GetLiabilityType() string {
	if x != nil {
		return x.LiabilityType
	}
	return ""
}

func (x *AddLiabilityRequest) GetOutstandingAmount() string {
	if x != nil {
		return x.OutstandingAmount
	}
	return ""
}

func (x *AddLiabilityRequest) GetMonthlyInstallment() string {
	if x != nil {
		return x.MonthlyInstallment
	}
	return ""
}

func (x *AddLiabilityRequest) GetInterestRate() string {
	if x != nil {
		return x.InterestRate
	}
	return ""
}

func (x *AddLiabilityRequest) GetMaturityDate() string {
	if x != nil {
		return x.MaturityDate
	}
	return ""
}

func (x *AddLiabilityRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type UpdateLiabilityRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId      string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	CreditorName       string                 `protobuf:"bytes,3,opt,name=creditor_name,json=creditorName,proto3" json:"creditor_name,omitempty"`
	LiabilityType      string                 `protobuf:"bytes,4,opt,name=liability_type,json=liabilityType,proto3" json:"liability_type,omitempty"`
	OutstandingAmount  string                 `protobuf:"bytes,5,opt,name=outstanding_amount,json=outstandingAmount,proto3" json:"outstanding_amount,omitempty"`
	MonthlyInstallment string                 `protobuf:"bytes,6,opt,name=monthly_installment,json=monthlyInstallment,proto3" json:"monthly_installment,omitempty"`
	InterestRate       string                 `protobuf:"bytes,7,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	MaturityDate       string                 `protobuf:"bytes,8,opt,name=maturity_date,json=maturityDate,proto3" json:"maturity_date,omitempty"`
	Source             string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateLiabilityRequest) Reset() {
	*x = UpdateLiabilityRequest{}
	mi := &file_financial_v1_financial_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLiabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLiabilityRequest) ProtoMessage() {}

func (x *UpdateLiabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLiabilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateLiabilityRequest) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateLiabilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetCreditorName() string {
	if x != nil {
		return x.CreditorName
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetLiabilityType() string {
	if x != nil {
		return x.LiabilityType
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetOutstandingAmount() string {
	if x != nil {
		return x.OutstandingAmount
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetMonthlyInstallment() string {
	if x != nil {
		return x.MonthlyInstallment
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetInterestRate() string {
	if x != nil {
		return x.InterestRate
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetMaturityDate() string {
	if x != nil {
		return x.MaturityDate
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListLiabilitiesByApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLiabilitiesByApplicationRequest) Reset() {
	*x = ListLiabilitiesByApplicationRequest{}
	mi := &file_financial_v1_financial_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLiabilitiesByApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLiabilitiesByApplicationRequest) ProtoMessage() {}

func (x *ListLiabilitiesByApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLiabilitiesByApplicationRequest.ProtoReflect.Descriptor instead.
func (*ListLiabilitiesByApplicationRequest) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{13}
}

func (x *ListLiabilitiesByApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListLiabilitiesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Liabilities   []*ApplicationLiability `protobuf:"bytes,1,rep,name=liabilities,proto3" json:"liabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLiabilitiesResponse) Reset() {
	*x = ListLiabilitiesResponse{}
	mi := &file_financial_v1_financial_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLiabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLiabilitiesResponse) ProtoMessage() {}

func (x *ListLiabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLiabilitiesResponse.ProtoReflect.Descriptor instead.
func (*ListLiabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{14}
}

func (x *ListLiabilitiesResponse) GetLiabilities() []*ApplicationLiability {
	if x != nil {
		return x.Liabilities
	}
	return nil
}

type CalculateFinancialRatiosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateFinancialRatiosRequest) Reset() {
	*x = CalculateFinancialRatiosRequest{}
	mi := &file_financial_v1_financial_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFinancialRatiosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFinancialRatiosRequest) ProtoMessage() {}

func (x *CalculateFinancialRatiosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFinancialRatiosRequest.ProtoReflect.Descriptor instead.
func (*CalculateFinancialRatiosRequest) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{15}
}

func (x *CalculateFinancialRatiosRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type ListFinancialRatiosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ratios        []*FinancialRatio      `protobuf:"bytes,1,rep,name=ratios,proto3" json:"ratios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFinancialRatiosResponse) Reset() {
	*x = ListFinancialRatiosResponse{}
	mi := &file_financial_v1_financial_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFinancialRatiosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFinancialRatiosResponse) ProtoMessage() {}

func (x *ListFinancialRatiosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_financial_v1_financial_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFinancialRatiosResponse.ProtoReflect.Descriptor instead.
func (*ListFinancialRatiosResponse) Descriptor() ([]byte, []int) {
	return file_financial_v1_financial_proto_rawDescGZIP(), []int{16}
}

func (x *ListFinancialRatiosResponse) GetRatios() []*FinancialRatio {
	if x != nil {
		return x.Ratios
	}
	return nil
}

var File_financial_v1_financial_proto protoreflect.FileDescriptor

const file_financial_v1_financial_proto_rawDesc = "" +
	"\n" +
	"\x1cfinancial/v1/financial.proto\x12\x10api.financial.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x02\n" +
	"\x18ApplicationFinancialFact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x17\n" +
	"\agl_code\x18\x03 \x01(\tR\x06glCode\x12\x1f\n" +
	"\vperiod_type\x18\x04 \x01(\tR\n" +
	"periodType\x12!\n" +
	"\fperiod_label\x18\x05 \x01(\tR\vperiodLabel\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12)\n" +
	"\x10confidence_level\x18\b \x01(\tR\x0fconfidenceLevel\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xff\x02\n" +
	"\x10ApplicationAsset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12&\n" +
	"\x0fasset_type_code\x18\x03 \x01(\tR\rassetTypeCode\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x04 \x01(\tR\tassetName\x12)\n" +
	"\x10ownership_status\x18\x05 \x01(\tR\x0fownershipStatus\x12)\n" +
	"\x10acquisition_year\x18\x06 \x01(\x05R\x0facquisitionYear\x12'\n" +
	"\x0festimated_value\x18\a \x01(\tR\x0eestimatedValue\x12)\n" +
	"\x10valuation_method\x18\b \x01(\tR\x0fvaluationMethod\x12#\n" +
	"\rlocation_text\x18\t \x01(\tR\flocationText\x12\x1e\n" +
	"\n" +
	"encumbered\x18\n" +
	" \x01(\bR\n" +
	"encumbered\"\xdb\x02\n" +
	"\x14ApplicationLiability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12#\n" +
	"\rcreditor_name\x18\x03 \x01(\tR\fcreditorName\x12%\n" +
	"\x0eliability_type\x18\x04 \x01(\tR\rliabilityType\x12-\n" +
	"\x12outstanding_amount\x18\x05 \x01(\tR\x11outstandingAmount\x12/\n" +
	"\x13monthly_installment\x18\x06 \x01(\tR\x12monthlyInstallment\x12#\n" +
	"\rinterest_rate\x18\a \x01(\tR\finterestRate\x12#\n" +
	"\rmaturity_date\x18\b \x01(\tR\fmaturityDate\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"\xf9\x01\n" +
	"\x0eFinancialRatio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x1d\n" +
	"\n" +
	"ratio_code\x18\x03 \x01(\tR\tratioCode\x12\x1f\n" +
	"\vratio_value\x18\x04 \x01(\tR\n" +
	"ratioValue\x12/\n" +
	"\x13calculation_version\x18\x05 \x01(\tR\x12calculationVersion\x12?\n" +
	"\rcalculated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcalculatedAt\"\xfb\x01\n" +
	"\x1aUpsertFinancialFactRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x17\n" +
	"\agl_code\x18\x02 \x01(\tR\x06glCode\x12\x1f\n" +
	"\vperiod_type\x18\x03 \x01(\tR\n" +
	"periodType\x12!\n" +
	"\fperiod_label\x18\x04 \x01(\tR\vperiodLabel\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12)\n" +
	"\x10confidence_level\x18\a \x01(\tR\x0fconfidenceLevel\"B\n" +
	"\x19ListFinancialFactsRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"^\n" +
	"\x1aListFinancialFactsResponse\x12@\n" +
	"\x05facts\x18\x01 \x03(\v2*.api.financial.v1.ApplicationFinancialFactR\x05facts\"\xee\x02\n" +
	"\x0fAddAssetRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12&\n" +
	"\x0fasset_type_code\x18\x02 \x01(\tR\rassetTypeCode\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x03 \x01(\tR\tassetName\x12)\n" +
	"\x10ownership_status\x18\x04 \x01(\tR\x0fownershipStatus\x12)\n" +
	"\x10acquisition_year\x18\x05 \x01(\x05R\x0facquisitionYear\x12'\n" +
	"\x0festimated_value\x18\x06 \x01(\tR\x0eestimatedValue\x12)\n" +
	"\x10valuation_method\x18\a \x01(\tR\x0fvaluationMethod\x12#\n" +
	"\rlocation_text\x18\b \x01(\tR\flocationText\x12\x1e\n" +
	"\n" +
	"encumbered\x18\t \x01(\bR\n" +
	"encumbered\"\x81\x03\n" +
	"\x12UpdateAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12&\n" +
	"\x0fasset_type_code\x18\x03 \x01(\tR\rassetTypeCode\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x04 \x01(\tR\tassetName\x12)\n" +
	"\x10ownership_status\x18\x05 \x01(\tR\x0fownershipStatus\x12)\n" +
	"\x10acquisition_year\x18\x06 \x01(\x05R\x0facquisitionYear\x12'\n" +
	"\x0festimated_value\x18\a \x01(\tR\x0eestimatedValue\x12)\n" +
	"\x10valuation_method\x18\b \x01(\tR\x0fvaluationMethod\x12#\n" +
	"\rlocation_text\x18\t \x01(\tR\flocationText\x12\x1e\n" +
	"\n" +
	"encumbered\x18\n" +
	" \x01(\bR\n" +
	"encumbered\"G\n" +
	"\x1eListAssetsByApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"P\n" +
	"\x12ListAssetsResponse\x12:\n" +
	"\x06assets\x18\x01 \x03(\v2\".api.financial.v1.ApplicationAssetR\x06assets\"\xca\x02\n" +
	"\x13AddLiabilityRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12#\n" +
	"\rcreditor_name\x18\x02 \x01(\tR\fcreditorName\x12%\n" +
	"\x0eliability_type\x18\x03 \x01(\tR\rliabilityType\x12-\n" +
	"\x12outstanding_amount\x18\x04 \x01(\tR\x11outstandingAmount\x12/\n" +
	"\x13monthly_installment\x18\x05 \x01(\tR\x12monthlyInstallment\x12#\n" +
	"\rinterest_rate\x18\x06 \x01(\tR\finterestRate\x12#\n" +
	"\rmaturity_date\x18\a \x01(\tR\fmaturityDate\x12\x16\n" +
	"\x06source\x18\b \x01(\tR\x06source\"\xdd\x02\n" +
	"\x16UpdateLiabilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12#\n" +
	"\rcreditor_name\x18\x03 \x01(\tR\fcreditorName\x12%\n" +
	"\x0eliability_type\x18\x04 \x01(\tR\rliabilityType\x12-\n" +
	"\x12outstanding_amount\x18\x05 \x01(\tR\x11outstandingAmount\x12/\n" +
	"\x13monthly_installment\x18\x06 \x01(\tR\x12monthlyInstallment\x12#\n" +
	"\rinterest_rate\x18\a \x01(\tR\finterestRate\x12#\n" +
	"\rmaturity_date\x18\b \x01(\tR\fmaturityDate\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"L\n" +
	"#ListLiabilitiesByApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"c\n" +
	"\x17ListLiabilitiesResponse\x12H\n" +
	"\vliabilities\x18\x01 \x03(\v2&.api.financial.v1.ApplicationLiabilityR\vliabilities\"H\n" +
	"\x1fCalculateFinancialRatiosRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\"W\n" +
	"\x1bListFinancialRatiosResponse\x128\n" +
	"\x06ratios\x18\x01 \x03(\v2 .api.financial.v1.FinancialRatioR\x06ratios2\xf3\v\n" +
	"\x10FinancialService\x12\xad\x01\n" +
	"\x13UpsertFinancialFact\x12,.api.financial.v1.UpsertFinancialFactRequest\x1a*.api.financial.v1.ApplicationFinancialFact\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v1/applications/{application_id}/financial-facts\x12\xaa\x01\n" +
	"\x12ListFinancialFacts\x12+.api.financial.v1.ListFinancialFactsRequest\x1a,.api.financial.v1.ListFinancialFactsResponse\"9\x82\xd3\xe4\x93\x023\x121/v1/applications/{application_id}/financial-facts\x12\x86\x01\n" +
	"\bAddAsset\x12!.api.financial.v1.AddAssetRequest\x1a\".api.financial.v1.ApplicationAsset\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/applications/{application_id}/assets\x12\x91\x01\n" +
	"\vUpdateAsset\x12$.api.financial.v1.UpdateAssetRequest\x1a\".api.financial.v1.ApplicationAsset\"8\x82\xd3\xe4\x93\x022:\x01*\x1a-/v1/applications/{application_id}/assets/{id}\x12\xa3\x01\n" +
	"\x17ListAssetsByApplication\x120.api.financial.v1.ListAssetsByApplicationRequest\x1a$.api.financial.v1.ListAssetsResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/applications/{application_id}/assets\x12\x97\x01\n" +
	"\fAddLiability\x12%.api.financial.v1.AddLiabilityRequest\x1a&.api.financial.v1.ApplicationLiability\"8\x82\xd3\xe4\x93\x022:\x01*\"-/v1/applications/{application_id}/liabilities\x12\xa2\x01\n" +
	"\x0fUpdateLiability\x12(.api.financial.v1.UpdateLiabilityRequest\x1a&.api.financial.v1.ApplicationLiability\"=\x82\xd3\xe4\x93\x027:\x01*\x1a2/v1/applications/{application_id}/liabilities/{id}\x12\xb7\x01\n" +
	"\x1cListLiabilitiesByApplication\x125.api.financial.v1.ListLiabilitiesByApplicationRequest\x1a).api.financial.v1.ListLiabilitiesResponse\"5\x82\xd3\xe4\x93\x02/\x12-/v1/applications/{application_id}/liabilities\x12\xc5\x01\n" +
	"\x18CalculateFinancialRatios\x121.api.financial.v1.CalculateFinancialRatiosRequest\x1a-.api.financial.v1.ListFinancialRatiosResponse\"G\x82\xd3\xe4\x93\x02A:\x01*\"</v1/applications/{application_id}/financial-ratios/calculateBB\n" +
	"\x10api.financial.v1P\x01Z,credit-analytics-backend/api/financial/v1;v1b\x06proto3"

var (
	file_financial_v1_financial_proto_rawDescOnce sync.Once
	file_financial_v1_financial_proto_rawDescData []byte
)

func file_financial_v1_financial_proto_rawDescGZIP() []byte {
	file_financial_v1_financial_proto_rawDescOnce.Do(func() {
		file_financial_v1_financial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_financial_v1_financial_proto_rawDesc), len(file_financial_v1_financial_proto_rawDesc)))
	})
	return file_financial_v1_financial_proto_rawDescData
}

var file_financial_v1_financial_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_financial_v1_financial_proto_goTypes = []any{
	(*ApplicationFinancialFact)(nil),            // 0: api.financial.v1.ApplicationFinancialFact
	(*ApplicationAsset)(nil),                    // 1: api.financial.v1.ApplicationAsset
	(*ApplicationLiability)(nil),                // 2: api.financial.v1.ApplicationLiability
	(*FinancialRatio)(nil),                      // 3: api.financial.v1.FinancialRatio
	(*UpsertFinancialFactRequest)(nil),          // 4: api.financial.v1.UpsertFinancialFactRequest
	(*ListFinancialFactsRequest)(nil),           // 5: api.financial.v1.ListFinancialFactsRequest
	(*ListFinancialFactsResponse)(nil),          // 6: api.financial.v1.ListFinancialFactsResponse
	(*AddAssetRequest)(nil),                     // 7: api.financial.v1.AddAssetRequest
	(*UpdateAssetRequest)(nil),                  // 8: api.financial.v1.UpdateAssetRequest
	(*ListAssetsByApplicationRequest)(nil),      // 9: api.financial.v1.ListAssetsByApplicationRequest
	(*ListAssetsResponse)(nil),                  // 10: api.financial.v1.ListAssetsResponse
	(*AddLiabilityRequest)(nil),                 // 11: api.financial.v1.AddLiabilityRequest
	(*UpdateLiabilityRequest)(nil),              // 12: api.financial.v1.UpdateLiabilityRequest
	(*ListLiabilitiesByApplicationRequest)(nil), // 13: api.financial.v1.ListLiabilitiesByApplicationRequest
	(*ListLiabilitiesResponse)(nil),             // 14: api.financial.v1.ListLiabilitiesResponse
	(*CalculateFinancialRatiosRequest)(nil),     // 15: api.financial.v1.CalculateFinancialRatiosRequest
	(*ListFinancialRatiosResponse)(nil),         // 16: api.financial.v1.ListFinancialRatiosResponse
	(*timestamppb.Timestamp)(nil),               // 17: google.protobuf.Timestamp
}
var file_financial_v1_financial_proto_depIdxs = []int32{
	17, // 0: api.financial.v1.ApplicationFinancialFact.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: api.financial.v1.FinancialRatio.calculated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.financial.v1.ListFinancialFactsResponse.facts:type_name -> api.financial.v1.ApplicationFinancialFact
	1,  // 3: api.financial.v1.ListAssetsResponse.assets:type_name -> api.financial.v1.ApplicationAsset
	2,  // 4: api.financial.v1.ListLiabilitiesResponse.liabilities:type_name -> api.financial.v1.ApplicationLiability
	3,  // 5: api.financial.v1.ListFinancialRatiosResponse.ratios:type_name -> api.financial.v1.FinancialRatio
	4,  // 6: api.financial.v1.FinancialService.UpsertFinancialFact:input_type -> api.financial.v1.UpsertFinancialFactRequest
	5,  // 7: api.financial.v1.FinancialService.ListFinancialFacts:input_type -> api.financial.v1.ListFinancialFactsRequest
	7,  // 8: api.financial.v1.FinancialService.AddAsset:input_type -> api.financial.v1.AddAssetRequest
	8,  // 9: api.financial.v1.FinancialService.UpdateAsset:input_type -> api.financial.v1.UpdateAssetRequest
	9,  // 10: api.financial.v1.FinancialService.ListAssetsByApplication:input_type -> api.financial.v1.ListAssetsByApplicationRequest
	11, // 11: api.financial.v1.FinancialService.AddLiability:input_type -> api.financial.v1.AddLiabilityRequest
	12, // 12: api.financial.v1.FinancialService.UpdateLiability:input_type -> api.financial.v1.UpdateLiabilityRequest
	13, // 13: api.financial.v1.FinancialService.ListLiabilitiesByApplication:input_type -> api.financial.v1.ListLiabilitiesByApplicationRequest
	15, // 14: api.financial.v1.FinancialService.CalculateFinancialRatios:input_type -> api.financial.v1.CalculateFinancialRatiosRequest
	0,  // 15: api.financial.v1.FinancialService.UpsertFinancialFact:output_type -> api.financial.v1.ApplicationFinancialFact
	6,  // 16: api.financial.v1.FinancialService.ListFinancialFacts:output_type -> api.financial.v1.ListFinancialFactsResponse
	1,  // 17: api.financial.v1.FinancialService.AddAsset:output_type -> api.financial.v1.ApplicationAsset
	1,  // 18: api.financial.v1.FinancialService.UpdateAsset:output_type -> api.financial.v1.ApplicationAsset
	10, // 19: api.financial.v1.FinancialService.ListAssetsByApplication:output_type -> api.financial.v1.ListAssetsResponse
	2,  // 20: api.financial.v1.FinancialService.AddLiability:output_type -> api.financial.v1.ApplicationLiability
	2,  // 21: api.financial.v1.FinancialService.UpdateLiability:output_type -> api.financial.v1.ApplicationLiability
	14, // 22: api.financial.v1.FinancialService.ListLiabilitiesByApplication:output_type -> api.financial.v1.ListLiabilitiesResponse
	16, // 23: api.financial.v1.FinancialService.CalculateFinancialRatios:output_type -> api.financial.v1.ListFinancialRatiosResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_financial_v1_financial_proto_init() }
func file_financial_v1_financial_proto_init() {
	if File_financial_v1_financial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_financial_v1_financial_proto_rawDesc), len(file_financial_v1_financial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_financial_v1_financial_proto_goTypes,
		DependencyIndexes: file_financial_v1_financial_proto_depIdxs,
		MessageInfos:      file_financial_v1_financial_proto_msgTypes,
	}.Build()
	File_financial_v1_financial_proto = out.File
	file_financial_v1_financial_proto_goTypes = nil
	file_financial_v1_financial_proto_depIdxs = nil
}
