// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: financial/v1/financial.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFinancialServiceAddAsset = "/api.financial.v1.FinancialService/AddAsset"
const OperationFinancialServiceAddLiability = "/api.financial.v1.FinancialService/AddLiability"
const OperationFinancialServiceCalculateFinancialRatios = "/api.financial.v1.FinancialService/CalculateFinancialRatios"
const OperationFinancialServiceListAssetsByApplication = "/api.financial.v1.FinancialService/ListAssetsByApplication"
const OperationFinancialServiceListFinancialFacts = "/api.financial.v1.FinancialService/ListFinancialFacts"
const OperationFinancialServiceListLiabilitiesByApplication = "/api.financial.v1.FinancialService/ListLiabilitiesByApplication"
const OperationFinancialServiceUpdateAsset = "/api.financial.v1.FinancialService/UpdateAsset"
const OperationFinancialServiceUpdateLiability = "/api.financial.v1.FinancialService/UpdateLiability"
const OperationFinancialServiceUpsertFinancialFact = "/api.financial.v1.FinancialService/UpsertFinancialFact"

type FinancialServiceHTTPServer interface {
	AddAsset(context.Context, *AddAssetRequest) (*ApplicationAsset, error)
	AddLiability(context.Context, *AddLiabilityRequest) (*ApplicationLiability, error)
	CalculateFinancialRatios(context.Context, *CalculateFinancialRatiosRequest) (*ListFinancialRatiosResponse, error)
	ListAssetsByApplication(context.Context, *ListAssetsByApplicationRequest) (*ListAssetsResponse, error)
	ListFinancialFacts(context.Context, *ListFinancialFactsRequest) (*ListFinancialFactsResponse, error)
	ListLiabilitiesByApplication(context.Context, *ListLiabilitiesByApplicationRequest) (*ListLiabilitiesResponse, error)
	UpdateAsset(context.Context, *UpdateAssetRequest) (*ApplicationAsset, error)
	UpdateLiability(context.Context, *UpdateLiabilityRequest) (*ApplicationLiability, error)
	UpsertFinancialFact(context.Context, *UpsertFinancialFactRequest) (*ApplicationFinancialFact, error)
}

func RegisterFinancialServiceHTTPServer(s *http.Server, srv FinancialServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/applications/{application_id}/financial-facts", _FinancialService_UpsertFinancialFact0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/financial-facts", _FinancialService_ListFinancialFacts0_HTTP_Handler(srv))
	r.POST("/v1/applications/{application_id}/assets", _FinancialService_AddAsset0_HTTP_Handler(srv))
	r.PUT("/v1/applications/{application_id}/assets/{id}", _FinancialService_UpdateAsset0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/assets", _FinancialService_ListAssetsByApplication0_HTTP_Handler(srv))
	r.POST("/v1/applications/{application_id}/liabilities", _FinancialService_AddLiability0_HTTP_Handler(srv))
	r.PUT("/v1/applications/{application_id}/liabilities/{id}", _FinancialService_UpdateLiability0_HTTP_Handler(srv))
	r.GET("/v1/applications/{application_id}/liabilities", _FinancialService_ListLiabilitiesByApplication0_HTTP_Handler(srv))
	r.POST("/v1/applications/{application_id}/financial-ratios/calculate", _FinancialService_CalculateFinancialRatios0_HTTP_Handler(srv))
}

func _FinancialService_UpsertFinancialFact0_HTTP_Handler(srv FinancialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertFinancialFactRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialServiceUpsertFinancialFact)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertFinancialFact(ctx, req.(*UpsertFinancialFactRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationFinancialFact)
		return ctx.Result(200, reply)
	}
}

func _FinancialService_ListFinancialFacts0_HTTP_Handler(srv FinancialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFinancialFactsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialServiceListFinancialFacts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFinancialFacts(ctx, req.(*ListFinancialFactsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFinancialFactsResponse)
		return ctx.Result(200, reply)
	}
}

func _FinancialService_AddAsset0_HTTP_Handler(srv FinancialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddAssetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialServiceAddAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddAsset(ctx, req.(*AddAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationAsset)
		return ctx.Result(200, reply)
	}
}

func _FinancialService_UpdateAsset0_HTTP_Handler(srv FinancialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAssetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialServiceUpdateAsset)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAsset(ctx, req.(*UpdateAssetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationAsset)
		return ctx.Result(200, reply)
	}
}

func _FinancialService_ListAssetsByApplication0_HTTP_Handler(srv FinancialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAssetsByApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialServiceListAssetsByApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAssetsByApplication(ctx, req.(*ListAssetsByApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAssetsResponse)
		return ctx.Result(200, reply)
	}
}

func _FinancialService_AddLiability0_HTTP_Handler(srv FinancialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddLiabilityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialServiceAddLiability)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddLiability(ctx, req.(*AddLiabilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationLiability)
		return ctx.Result(200, reply)
	}
}

func _FinancialService_UpdateLiability0_HTTP_Handler(srv FinancialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateLiabilityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialServiceUpdateLiability)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateLiability(ctx, req.(*UpdateLiabilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplicationLiability)
		return ctx.Result(200, reply)
	}
}

func _FinancialService_ListLiabilitiesByApplication0_HTTP_Handler(srv FinancialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLiabilitiesByApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialServiceListLiabilitiesByApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLiabilitiesByApplication(ctx, req.(*ListLiabilitiesByApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLiabilitiesResponse)
		return ctx.Result(200, reply)
	}
}

func _FinancialService_CalculateFinancialRatios0_HTTP_Handler(srv FinancialServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CalculateFinancialRatiosRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFinancialServiceCalculateFinancialRatios)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CalculateFinancialRatios(ctx, req.(*CalculateFinancialRatiosRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFinancialRatiosResponse)
		return ctx.Result(200, reply)
	}
}

type FinancialServiceHTTPClient interface {
	AddAsset(ctx context.Context, req *AddAssetRequest, opts ...http.CallOption) (rsp *ApplicationAsset, err error)
	AddLiability(ctx context.Context, req *AddLiabilityRequest, opts ...http.CallOption) (rsp *ApplicationLiability, err error)
	CalculateFinancialRatios(ctx context.Context, req *CalculateFinancialRatiosRequest, opts ...http.CallOption) (rsp *ListFinancialRatiosResponse, err error)
	ListAssetsByApplication(ctx context.Context, req *ListAssetsByApplicationRequest, opts ...http.CallOption) (rsp *ListAssetsResponse, err error)
	ListFinancialFacts(ctx context.Context, req *ListFinancialFactsRequest, opts ...http.CallOption) (rsp *ListFinancialFactsResponse, err error)
	ListLiabilitiesByApplication(ctx context.Context, req *ListLiabilitiesByApplicationRequest, opts ...http.CallOption) (rsp *ListLiabilitiesResponse, err error)
	UpdateAsset(ctx context.Context, req *UpdateAssetRequest, opts ...http.CallOption) (rsp *ApplicationAsset, err error)
	UpdateLiability(ctx context.Context, req *UpdateLiabilityRequest, opts ...http.CallOption) (rsp *ApplicationLiability, err error)
	UpsertFinancialFact(ctx context.Context, req *UpsertFinancialFactRequest, opts ...http.CallOption) (rsp *ApplicationFinancialFact, err error)
}

type FinancialServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewFinancialServiceHTTPClient(client *http.Client) FinancialServiceHTTPClient {
	return &FinancialServiceHTTPClientImpl{client}
}

func (c *FinancialServiceHTTPClientImpl) AddAsset(ctx context.Context, in *AddAssetRequest, opts ...http.CallOption) (*ApplicationAsset, error) {
	var out ApplicationAsset
	pattern := "/v1/applications/{application_id}/assets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialServiceAddAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialServiceHTTPClientImpl) AddLiability(ctx context.Context, in *AddLiabilityRequest, opts ...http.CallOption) (*ApplicationLiability, error) {
	var out ApplicationLiability
	pattern := "/v1/applications/{application_id}/liabilities"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialServiceAddLiability))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialServiceHTTPClientImpl) CalculateFinancialRatios(ctx context.Context, in *CalculateFinancialRatiosRequest, opts ...http.CallOption) (*ListFinancialRatiosResponse, error) {
	var out ListFinancialRatiosResponse
	pattern := "/v1/applications/{application_id}/financial-ratios/calculate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialServiceCalculateFinancialRatios))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialServiceHTTPClientImpl) ListAssetsByApplication(ctx context.Context, in *ListAssetsByApplicationRequest, opts ...http.CallOption) (*ListAssetsResponse, error) {
	var out ListAssetsResponse
	pattern := "/v1/applications/{application_id}/assets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFinancialServiceListAssetsByApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialServiceHTTPClientImpl) ListFinancialFacts(ctx context.Context, in *ListFinancialFactsRequest, opts ...http.CallOption) (*ListFinancialFactsResponse, error) {
	var out ListFinancialFactsResponse
	pattern := "/v1/applications/{application_id}/financial-facts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFinancialServiceListFinancialFacts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialServiceHTTPClientImpl) ListLiabilitiesByApplication(ctx context.Context, in *ListLiabilitiesByApplicationRequest, opts ...http.CallOption) (*ListLiabilitiesResponse, error) {
	var out ListLiabilitiesResponse
	pattern := "/v1/applications/{application_id}/liabilities"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFinancialServiceListLiabilitiesByApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialServiceHTTPClientImpl) UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...http.CallOption) (*ApplicationAsset, error) {
	var out ApplicationAsset
	pattern := "/v1/applications/{application_id}/assets/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialServiceUpdateAsset))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialServiceHTTPClientImpl) UpdateLiability(ctx context.Context, in *UpdateLiabilityRequest, opts ...http.CallOption) (*ApplicationLiability, error) {
	var out ApplicationLiability
	pattern := "/v1/applications/{application_id}/liabilities/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialServiceUpdateLiability))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FinancialServiceHTTPClientImpl) UpsertFinancialFact(ctx context.Context, in *UpsertFinancialFactRequest, opts ...http.CallOption) (*ApplicationFinancialFact, error) {
	var out ApplicationFinancialFact
	pattern := "/v1/applications/{application_id}/financial-facts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFinancialServiceUpsertFinancialFact))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
