// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: financial/v1/financial.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FinancialService_UpsertFinancialFact_FullMethodName          = "/api.financial.v1.FinancialService/UpsertFinancialFact"
	FinancialService_ListFinancialFacts_FullMethodName           = "/api.financial.v1.FinancialService/ListFinancialFacts"
	FinancialService_AddAsset_FullMethodName                     = "/api.financial.v1.FinancialService/AddAsset"
	FinancialService_UpdateAsset_FullMethodName                  = "/api.financial.v1.FinancialService/UpdateAsset"
	FinancialService_ListAssetsByApplication_FullMethodName      = "/api.financial.v1.FinancialService/ListAssetsByApplication"
	FinancialService_AddLiability_FullMethodName                 = "/api.financial.v1.FinancialService/AddLiability"
	FinancialService_UpdateLiability_FullMethodName              = "/api.financial.v1.FinancialService/UpdateLiability"
	FinancialService_ListLiabilitiesByApplication_FullMethodName = "/api.financial.v1.FinancialService/ListLiabilitiesByApplication"
	FinancialService_CalculateFinancialRatios_FullMethodName     = "/api.financial.v1.FinancialService/CalculateFinancialRatios"
)

// FinancialServiceClient is the client API for FinancialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinancialServiceClient interface {
	UpsertFinancialFact(ctx context.Context, in *UpsertFinancialFactRequest, opts ...grpc.CallOption) (*ApplicationFinancialFact, error)
	ListFinancialFacts(ctx context.Context, in *ListFinancialFactsRequest, opts ...grpc.CallOption) (*ListFinancialFactsResponse, error)
	AddAsset(ctx context.Context, in *AddAssetRequest, opts ...grpc.CallOption) (*ApplicationAsset, error)
	UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*ApplicationAsset, error)
	ListAssetsByApplication(ctx context.Context, in *ListAssetsByApplicationRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error)
	AddLiability(ctx context.Context, in *AddLiabilityRequest, opts ...grpc.CallOption) (*ApplicationLiability, error)
	UpdateLiability(ctx context.Context, in *UpdateLiabilityRequest, opts ...grpc.CallOption) (*ApplicationLiability, error)
	ListLiabilitiesByApplication(ctx context.Context, in *ListLiabilitiesByApplicationRequest, opts ...grpc.CallOption) (*ListLiabilitiesResponse, error)
	CalculateFinancialRatios(ctx context.Context, in *CalculateFinancialRatiosRequest, opts ...grpc.CallOption) (*ListFinancialRatiosResponse, error)
}

type financialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinancialServiceClient(cc grpc.ClientConnInterface) FinancialServiceClient {
	return &financialServiceClient{cc}
}

func (c *financialServiceClient) UpsertFinancialFact(ctx context.Context, in *UpsertFinancialFactRequest, opts ...grpc.CallOption) (*ApplicationFinancialFact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationFinancialFact)
	err := c.cc.Invoke(ctx, FinancialService_UpsertFinancialFact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialServiceClient) ListFinancialFacts(ctx context.Context, in *ListFinancialFactsRequest, opts ...grpc.CallOption) (*ListFinancialFactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFinancialFactsResponse)
	err := c.cc.Invoke(ctx, FinancialService_ListFinancialFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialServiceClient) AddAsset(ctx context.Context, in *AddAssetRequest, opts ...grpc.CallOption) (*ApplicationAsset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationAsset)
	err := c.cc.Invoke(ctx, FinancialService_AddAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialServiceClient) UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*ApplicationAsset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationAsset)
	err := c.cc.Invoke(ctx, FinancialService_UpdateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialServiceClient) ListAssetsByApplication(ctx context.Context, in *ListAssetsByApplicationRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssetsResponse)
	err := c.cc.Invoke(ctx, FinancialService_ListAssetsByApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialServiceClient) AddLiability(ctx context.Context, in *AddLiabilityRequest, opts ...grpc.CallOption) (*ApplicationLiability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationLiability)
	err := c.cc.Invoke(ctx, FinancialService_AddLiability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialServiceClient) UpdateLiability(ctx context.Context, in *UpdateLiabilityRequest, opts ...grpc.CallOption) (*ApplicationLiability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationLiability)
	err := c.cc.Invoke(ctx, FinancialService_UpdateLiability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialServiceClient) ListLiabilitiesByApplication(ctx context.Context, in *ListLiabilitiesByApplicationRequest, opts ...grpc.CallOption) (*ListLiabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLiabilitiesResponse)
	err := c.cc.Invoke(ctx, FinancialService_ListLiabilitiesByApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialServiceClient) CalculateFinancialRatios(ctx context.Context, in *CalculateFinancialRatiosRequest, opts ...grpc.CallOption) (*ListFinancialRatiosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFinancialRatiosResponse)
	err := c.cc.Invoke(ctx, FinancialService_CalculateFinancialRatios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialServiceServer is the server API for FinancialService service.
// All implementations must embed UnimplementedFinancialServiceServer
// for forward compatibility.
type FinancialServiceServer interface {
	UpsertFinancialFact(context.Context, *UpsertFinancialFactRequest) (*ApplicationFinancialFact, error)
	ListFinancialFacts(context.Context, *ListFinancialFactsRequest) (*ListFinancialFactsResponse, error)
	AddAsset(context.Context, *AddAssetRequest) (*ApplicationAsset, error)
	UpdateAsset(context.Context, *UpdateAssetRequest) (*ApplicationAsset, error)
	ListAssetsByApplication(context.Context, *ListAssetsByApplicationRequest) (*ListAssetsResponse, error)
	AddLiability(context.Context, *AddLiabilityRequest) (*ApplicationLiability, error)
	UpdateLiability(context.Context, *UpdateLiabilityRequest) (*ApplicationLiability, error)
	ListLiabilitiesByApplication(context.Context, *ListLiabilitiesByApplicationRequest) (*ListLiabilitiesResponse, error)
	CalculateFinancialRatios(context.Context, *CalculateFinancialRatiosRequest) (*ListFinancialRatiosResponse, error)
	mustEmbedUnimplementedFinancialServiceServer()
}

// UnimplementedFinancialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinancialServiceServer struct{}

func (UnimplementedFinancialServiceServer) UpsertFinancialFact(context.Context, *UpsertFinancialFactRequest) (*ApplicationFinancialFact, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertFinancialFact not implemented")
}
func (UnimplementedFinancialServiceServer) ListFinancialFacts(context.Context, *ListFinancialFactsRequest) (*ListFinancialFactsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFinancialFacts not implemented")
}
func (UnimplementedFinancialServiceServer) AddAsset(context.Context, *AddAssetRequest) (*ApplicationAsset, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAsset not implemented")
}
func (UnimplementedFinancialServiceServer) UpdateAsset(context.Context, *UpdateAssetRequest) (*ApplicationAsset, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAsset not implemented")
}
func (UnimplementedFinancialServiceServer) ListAssetsByApplication(context.Context, *ListAssetsByApplicationRequest) (*ListAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssetsByApplication not implemented")
}
func (UnimplementedFinancialServiceServer) AddLiability(context.Context, *AddLiabilityRequest) (*ApplicationLiability, error) {
	return nil, status.Error(codes.Unimplemented, "method AddLiability not implemented")
}
func (UnimplementedFinancialServiceServer) UpdateLiability(context.Context, *UpdateLiabilityRequest) (*ApplicationLiability, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLiability not implemented")
}
func (UnimplementedFinancialServiceServer) ListLiabilitiesByApplication(context.Context, *ListLiabilitiesByApplicationRequest) (*ListLiabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLiabilitiesByApplication not implemented")
}
func (UnimplementedFinancialServiceServer) CalculateFinancialRatios(context.Context, *CalculateFinancialRatiosRequest) (*ListFinancialRatiosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateFinancialRatios not implemented")
}
func (UnimplementedFinancialServiceServer) mustEmbedUnimplementedFinancialServiceServer() {}
func (UnimplementedFinancialServiceServer) testEmbeddedByValue()                          {}

// UnsafeFinancialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinancialServiceServer will
// result in compilation errors.
type UnsafeFinancialServiceServer interface {
	mustEmbedUnimplementedFinancialServiceServer()
}

func RegisterFinancialServiceServer(s grpc.ServiceRegistrar, srv FinancialServiceServer) {
	// If the following call panics, it indicates UnimplementedFinancialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinancialService_ServiceDesc, srv)
}

func _FinancialService_UpsertFinancialFact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertFinancialFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServiceServer).UpsertFinancialFact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialService_UpsertFinancialFact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServiceServer).UpsertFinancialFact(ctx, req.(*UpsertFinancialFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialService_ListFinancialFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFinancialFactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServiceServer).ListFinancialFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialService_ListFinancialFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServiceServer).ListFinancialFacts(ctx, req.(*ListFinancialFactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialService_AddAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServiceServer).AddAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialService_AddAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServiceServer).AddAsset(ctx, req.(*AddAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialService_UpdateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServiceServer).UpdateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialService_UpdateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServiceServer).UpdateAsset(ctx, req.(*UpdateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialService_ListAssetsByApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetsByApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServiceServer).ListAssetsByApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialService_ListAssetsByApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServiceServer).ListAssetsByApplication(ctx, req.(*ListAssetsByApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialService_AddLiability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLiabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServiceServer).AddLiability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialService_AddLiability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServiceServer).AddLiability(ctx, req.(*AddLiabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialService_UpdateLiability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLiabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServiceServer).UpdateLiability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialService_UpdateLiability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServiceServer).UpdateLiability(ctx, req.(*UpdateLiabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialService_ListLiabilitiesByApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLiabilitiesByApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServiceServer).ListLiabilitiesByApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialService_ListLiabilitiesByApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServiceServer).ListLiabilitiesByApplication(ctx, req.(*ListLiabilitiesByApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialService_CalculateFinancialRatios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateFinancialRatiosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialServiceServer).CalculateFinancialRatios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialService_CalculateFinancialRatios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialServiceServer).CalculateFinancialRatios(ctx, req.(*CalculateFinancialRatiosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinancialService_ServiceDesc is the grpc.ServiceDesc for FinancialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinancialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.financial.v1.FinancialService",
	HandlerType: (*FinancialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertFinancialFact",
			Handler:    _FinancialService_UpsertFinancialFact_Handler,
		},
		{
			MethodName: "ListFinancialFacts",
			Handler:    _FinancialService_ListFinancialFacts_Handler,
		},
		{
			MethodName: "AddAsset",
			Handler:    _FinancialService_AddAsset_Handler,
		},
		{
			MethodName: "UpdateAsset",
			Handler:    _FinancialService_UpdateAsset_Handler,
		},
		{
			MethodName: "ListAssetsByApplication",
			Handler:    _FinancialService_ListAssetsByApplication_Handler,
		},
		{
			MethodName: "AddLiability",
			Handler:    _FinancialService_AddLiability_Handler,
		},
		{
			MethodName: "UpdateLiability",
			Handler:    _FinancialService_UpdateLiability_Handler,
		},
		{
			MethodName: "ListLiabilitiesByApplication",
			Handler:    _FinancialService_ListLiabilitiesByApplication_Handler,
		},
		{
			MethodName: "CalculateFinancialRatios",
			Handler:    _FinancialService_CalculateFinancialRatios_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "financial/v1/financial.proto",
}
